.ocamlformat

This is the most recent stable version, the later versions have some
other issues.

Fix ocamlformat version

---

coq/dune
coq/init.ml
coq/loader.ml
coq/loader.mli
fleche/debug.ml

This is just a copy from SerAPI's one for now, but it belongs here.

[coq] Add plugin loader library.

---

README.md

ps-id: d2201c1b-5331-4393-95a6-97b67d7f7d44

elaborate install instructions for editor/code in README

---

Makefile
coq-lsp.opam

This seems to be problematic for the CI, seems like a mystery to me.

[build] Also build ltac2 in the composed setup.

---

examples/T2048.v

This is a fun one but also eats a lot of memory.
ps-id: d3b9d704-e8d1-4882-8245-4e75e7519a95

[example] add 2048 example

---

controller/coq_lsp.ml
fleche/doc.ml
fleche/types.ml
fleche/types.mli

cc @corwin-of-amber ; this should be a base for what we discussed, I copied the code from jscoq I hope that correctly.
Actually there is no need to add any specific method, to update the loadpath, just call `Fleche.Doc.create` from the worker with the new parameters.

[diagnostics] Add extra information on Require Error.

---

controller/coq_lsp.ml
editor/code/package.json
fleche/config.ml
fleche/info.ml
fleche/info.mli

This is still configurable by an option.

[goals] Show the goal _before_ running the tactic at point

---

editor/code/src/client.ts
editor/code/src/goals.ts

We need to make this much more principled, but for 0.1.0 this will work fine IMHO.

[goal panel] (Hacky) fix for panel lifetime

---

Makefile

Useful for quickly purging the submodules.

[makefile] add submodules-deinit target

---

.gitignore

This is the output of nix build

chore(ci): add result/ to .gitignore

---

.github/workflows/build.yml
CHANGES.md
coq-lsp.opam
dune-project

Current setup was too restrictive for users.

[ci] Support OCaml 4.12 onwards

---

controller/coq_lsp.ml
coq/init.ml

[vendor] Bump Coq and SerAPI to master

---

controller/coq_lsp.ml

This was clearly wrong, and due to my own laziness.
We now store instead the uri of the pending document, and retrieve its state from the document table for checking.

[lsp] Don't replay full LSP methods on checking resumption

---

CHANGES.md
controller/coq_lsp.ml
editor/code/media/styles.css
editor/code/src/client.ts
editor/code/src/goals.ts
etc/doc/PROTOCOL.md

[goals] Display position for goals, handle multiple goals better.

---

fleche/doc.ml

Up to now, we stored error recovery states in a global variable. This doesn't play well with more advanced resumption setups.
We use a more robust approach (tho still far from final), and scan the document back for a recovery candidate. This is much better, and although it has a linear cost until we optimize it, should be much more robust, and allow the implementation of #90 in a very easy way.

[fleche] Remove hack for error recovery state

---

.github/workflows/build.yml

ci: remove duplication between macos and ubuntu jobs

---

.github/workflows/build.yml
.gitmodules
flake.lock
flake.nix

I've also removed some duplication between the macos and ubuntu jobs since we can be specific about combinations we actually want to check.

chore(ci): add Nix to CI

---

controller/coq_lsp.ml

[controller] Handle failing requests better.

---

controller/coq_lsp.ml
controller/dune
controller/version.ml
controller/version.mli

This should make it easier to update the version when doing a release.

[server] add version string in separate file and update version, fix bug

---

controller/cache.ml
controller/cache.mli
controller/coq_lsp.ml
controller/doc_manager.ml
controller/doc_manager.mli
controller/dune
controller/lsp_util.ml
controller/lsp_util.mli
controller/requests.ml
controller/requests.mli

The moment has come, we must fix the lsp init sequence before splitting more; this will still significantly change when document updates can trigger requests.

[controller] Refactor into several files

---

coq/goals.ml
coq/loader.ml

[deps] Bump Coq and SerAPI to newer versions.

---

controller/coq_lsp.ml
controller/doc_manager.ml
controller/doc_manager.mli
controller/requests.ml
coq/init.mli
coq/interp.ml
coq/interp.mli
coq/parsing.mli
coq/print.ml
coq/print.mli
coq/protect.ml
coq/protect.mli
coq/state.mli
fleche/doc.ml
fleche/doc.mli
fleche/info.ml
fleche/info.mli
fleche/io.ml
fleche/io.mli
fleche/memo.ml
fleche/memo.mli

Next step is to control not only resumption, but ending, to which extent a refactoring is convenient as to separate concerns of what the document can do vs what the user desires to do.

[fleche] Some refactoring in preparation for a more controlled interp loop

---

coq/goals.ml
coq/goals.mli
coq/parsing.ml
coq/parsing.mli
coq/state.ml
coq/state.mli
fleche/doc.ml
fleche/info.ml

[api] Improvements on Coq API encapsulation.

---

controller/coq_lsp.ml
controller/doc_manager.ml
controller/requests.ml
coq/ast.ml
fleche/doc.ml
fleche/doc.mli

We will use this to wake up the current goal request.

[fleche] Allow to set cutoff point.

---

CHANGES.md
controller/requests.ml
fleche/doc.ml
fleche/doc.mli
fleche/info.ml
fleche/info.mli
fleche/stats.ml
fleche/stats.mli

Fixes #173
There are many improvements that we could do here.

[fleche] Store (and restore) global stats per-document.

---

examples/NewlinePrinter.v

Contributed-by: Ali Caglayan <alizter@gmail.com>

examples: add NewlinePrinter.v to test goal display

---

controller/coq_lsp.ml
controller/doc_manager.ml
fleche/doc.ml
fleche/doc.mli

In particular we separate the language of request answers from the language of request processing actions, towards a more principled delayed request queue.

[controller] Some refactoring for request handling

---

editor/code/CHANGELOG.md
editor/code/src/client.ts

I'm unsure we can do better.
Closes #183

[code] Check for VSCoq and complain about a possible conflict.

---

editor/code/src/client.ts
editor/code/src/progress.ts

We clarify state ownership, this is much cleaner and closer to web development standards.

[code] Refactor fileProgress client logic.

---

CONTRIBUTING.md
README.md
etc/ContributionIdeas.md

Tried to streamline the intro a bit.

[README] Pass and update.

---

editor/code/lib/types.ts
editor/code/src/client.ts
editor/code/src/goals.ts
editor/code/view/infoview.ts
etc/doc/PROTOCOL.md

We now handle the lifetime properly, and decouple the client from the lifetime of the panel.
This is a contribution towards #186

[info panel] Refactor panel to proper object.

---

controller/coq_lsp.ml

We need to lift the error handling from `dispatch_message` to `dispatch_or_resume_check` as we need to cover problem in `resume_check` and request wakeup.

[controller] Scope request error handling properly.

---

controller/coq_lsp.ml
controller/doc_manager.ml
controller/doc_manager.mli
controller/dune
controller/rq_init.ml
controller/rq_init.mli

This is required to have completion and goals working properly together.

[doc_manager] Allow to postpone more than one position request.

---

CHANGES.md
controller/requests.ml
editor/code/lib/types.ts
editor/code/src/goals.ts
editor/code/views/info/goalRender.ts
editor/code/views/info/index.ts
etc/doc/PROTOCOL.md

We now:
- provide a generic TS interface for the goals
- fill stack and def

[server] Improve `GoalAnswer` request response.

---

CHANGES.md
controller/coq_lsp.ml
editor/code/package.json
editor/code/src/config.ts
fleche/config.ml

This is a simpler version of #217
Co-authored-by: Ali Caglayan <alizter@gmail.com>

[config] Add debug client option.

---

Makefile

Revert "[Makefile] coq configure prefix and add nostdlib make"

---

controller/requests.ml
coq/goals.ml
coq/goals.mli
fleche/doc.ml
fleche/types.ml
fleche/types.mli
lsp/jCoq.ml
lsp/jFleche.ml
lsp/jFleche.mli

Still not done, but this is a good checkpoint.

[lsp] More rework of LSP serialization.

---

controller/requests.ml
fleche/doc.ml
fleche/doc.mli

[doc] Make global stats structure incremental

---

CHANGES.md
coq/init.ml
coq/init.mli
coq/workspace.ml
coq/workspace.mli
fleche/doc.ml
lsp/base.ml

This will be important when we start compiling files.

[coq] Fix libname calculation.

---

lsp/jFleche.ml

We were sending the message as a `Pp.t` instead of what LSP expects.

[lsp] Fix serialization of diagnostics

---

controller/rq_completion.ml
fleche/config.ml

add small completion list for internal debugging

---

CHANGES.md
editor/code/views/info/Info.tsx

We forgot to put each message into its own element.

[info] Fix messages panel rendering after port to react.

---

coq/goals.ml

Adapt w.r.t. coq/coq#17170.

---

CHANGES.md
editor/code/views/info/Info.tsx

Reported-by: Hugo Herbelin <Hugo.Herbelin@inria.fr>

infoview/goals: fix off-by-one error in goal numbering

---

editor/code/views/info/CoqPp.tsx
editor/code/views/info/Details.tsx
editor/code/views/info/Goals.tsx
editor/code/views/info/Info.tsx
editor/code/views/info/Message.tsx

Co-authored-by: Ramkumar Ramachandra <r@artagnon.com>

[info] Split React components into proper modules

---

controller/doc_manager.ml
controller/doc_manager.mli
controller/lsp_core.ml
coq/protect.ml
coq/protect.mli
examples/exerciseTest.wpn
fleche/contents.ml
fleche/contents.mli
fleche/doc.ml
fleche/doc.mli

This should allow us to have finer parsing and even more formats, such as waterproof.

[fleche] Generalize contents type

---

CHANGES.md
editor/code/views/info/Goals.tsx

This is a quick fix.
Closes #293

[goals] Display hypothesis with bodies.

---

controller/lsp_core.ml
controller/requests.ml
controller/requests.mli
controller/rq_goals.ml
controller/rq_goals.mli
controller/rq_hover.ml
controller/rq_hover.mli

We will later introduce a better interface.

[controller] Refactor requests to their own module.

---

CHANGES.md
coq/goals.ml
coq/goals.mli
etc/doc/PROTOCOL.md

Thanks to Alex Sanchez-Stern for the report / comment.

[doc] Add information about accepted URI types.

---

CHANGES.md
controller/doc_manager.ml
controller/doc_manager.mli
controller/lsp_core.ml
controller/rq_init.ml
coq/dune
coq/init.mli
coq/workspace.ml
coq/workspace.mli
examples/modα.v
fleche/contents.ml
fleche/contents.mli
fleche/doc.ml
fleche/doc.mli
fleche/io.ml
fleche/io.mli
lang/dune
lang/lUri.ml
lang/lUri.mli
lsp/base.ml
lsp/base.mli
lsp/doc.ml
lsp/doc.mli
lsp/jFleche.ml
lsp/jFleche.mli
lsp/jLang.ml

This should help preventing many issues that can happen due to bad URIs; still quite a bit of work to do here, but the code overall, while a bit uglier, seems safer.
Fixes #187

[lsp] Abstract URI type, improve URI validation.

---

CHANGES.md
controller/coq_lsp.ml
controller/rq_goals.ml
editor/code/views/info/media/messages.css
fleche/doc.ml

Fixes #308
We delay the resolution of #195 as the UI story for duplicating information is still not very clear.

[messages] Enable display of info and debug messages.

---

CHANGES.md
controller/rq_goals.ml
editor/code/lib/types.ts
editor/code/views/info/Message.tsx
editor/code/views/info/Messages.tsx
etc/doc/PROTOCOL.md
fleche/doc.ml
lsp/jFleche.ml
lsp/jFleche.mli

[messages] Print warnings in info panel

---

CHANGES.md
coq/protect.ml
coq/protect.mli
coq/state.ml
coq/state.mli
fleche/doc.ml
fleche/memo.mli

This is required for advanced stuff like #319

[fleche] Allow error recovery to execute dynamic commands

---

CHANGES.md
coq/protect.ml
coq/protect.mli
coq/state.ml
coq/state.mli
examples/goals.v
fleche/doc.ml

This is very useful when doing bulleted proofs.
Fixes #300

[doc] [error] Auto-admit bullets on new bullet error.

---

coq/ast.ml
fleche/doc.ml

[documentSymbol] Add some missing `detail` fields

---

README.md

Rendered
https://github.com/Alizter/coq-lsp/blob/ps/rr/doc_readme___add_table_of_contents__cleanup_title_headers_and_reorg/README.md

doc(README): add table of contents, cleanup title headers and reorg

---

CHANGES.md
controller/lsp_core.ml
controller/rq_definition.ml
controller/rq_definition.mli
controller/rq_init.ml
coq/ast.ml
coq/ast.mli
examples/ex0.v
fleche/doc.ml
fleche/doc.mli
lsp/jFleche.ml
lsp/jFleche.mli

Due to lack of workspace metadata, this only works for the same file.
Fixes #53

[lsp] Basic jump to definition support.

---

README.md

doc: README tweaks

---

CHANGES.md
controller/rq_common.ml
controller/rq_common.mli
controller/rq_definition.ml
controller/rq_hover.ml
coq/ast.ml
coq/ast.mli
fleche/doc.ml
fleche/info.ml
fleche/info.mli

This is very preliminary, for some reason hypothesis don't work,
also we need to print inductives.
Rendering can also be improved.
cc: #164

[hover] Show type of definitions on hover

---

README.md

Rendered:
https://github.com/Alizter/coq-lsp/blob/ps/rr/update_readme_about_hover/README.md

update README about hover

---

controller/rq_common.ml
controller/rq_common.mli
controller/rq_completion.ml
controller/rq_definition.ml
controller/rq_hover.ml
controller/rq_symbols.ml
coq/ast.ml
coq/ast.mli
fleche/doc.ml
fleche/doc.mli
lang/ast.ml
lang/ast.mli
lang/with_range.ml

This will make code more uniform.

[lang] Move Ast Info to lang.

---

CHANGES.md
coq/workspace.ml

We do a point release as this is important for many users.

[workspace] Fix handling of COQPATH and OCAMLPATH

---

CHANGES.md
controller/lsp_core.ml
controller/rq_document.ml
controller/rq_document.mli
editor/code/lib/types.ts
editor/code/package.json
editor/code/src/client.ts
etc/doc/PROTOCOL.md
lsp/jCoq.ml
lsp/jFleche.ml
lsp/jFleche.mli

cc: https://github.com/ejgallego/coq-serapi/pull/318

[protocol] New request `coq/getDocument` to get serialized document.

---

CHANGES.md
editor/code/package.json
editor/code/src/client.ts

[code] Option to ignore .vo files automatically

---

fleche/doc.ml

Until we implement #322 , this will help with #310

[doc] Refactor find_proof into ast finding + action

---

controller/dune
controller/lsp_core.ml
coq-lsp.opam
flake.nix

[misc] Use dune build info for refined version view.

---

controller/rq_completion.ml
controller/rq_definition.ml
controller/rq_hover.ml
controller/rq_symbols.ml
lsp/base.ml
lsp/base.mli
lsp/core.ml
lsp/core.mli
lsp/jCoq.ml
lsp/jFleche.ml
lsp/jFleche.mli
lsp/jLang.ml
lsp/jLang.mli

Extracted from #361 as it is of general interest.
We also so a bit of refactoring in terms of module org.

[lsp] Add progress, partial work, and pull diagnostics datatypes

---

CHANGES.md
editor/code/package.json
editor/code/src/client.ts

This is useful for testing, and a base to solve the issue in #209.

[code] Add commands to start / stop the server

---

CHANGES.md
controller/lsp_core.ml
test/.gitignore
test/.vscode/launch.json
test/jest.config.js
test/package-lock.json
test/package.json
test/src/LanguageServer.ts
test/src/Lifecycle.test.ts
test/tsconfig.json

~~Okay, this seems to be the right approach. However, there seems to be some problem with the server: it doesn't seem to exit when I issue "exit". I'm still debugging this.~~
This branch is ready with two lifecycle tests.

test: lay the foundation for testing with node

---

CHANGES.md
README.md
editor/code/package-lock.json
editor/code/package.json

[code] Update to language-client 8.1.0

---

CHANGES.md
README.md
editor/code/package.json
editor/code/src/client.ts
editor/code/src/goals.ts
editor/code/src/progress.ts
editor/code/views/info/Info.tsx

Thanks Ali for all the feedback on this.
Closes #209

[code] Provide status bar button to stop / start the server.

---

editor/code/views/info/Goals.tsx

This is a nit to silence React's linter.

[infoview] Pass key to label list

---

CHANGES.md
controller/lsp_core.ml
controller/rq_init.ml
controller/rq_lens.ml
controller/rq_lens.mli
lsp/core.ml
lsp/core.mli

This is just the infrastructure, we provide no lenses for now.

[protocol] Code lens infrastructure

---

README.md

doc: minor tweaks

---

README.md

emojify rest of readme

---

.github/workflows/build.yml
Makefile

We only have a couple of simple lifecycle tests at the moment.

ci: add jest-based testing

---

CHANGES.md
editor/code/views/info/Goals.tsx

This is not perfect, but still much better than what we have now.
Fixes #381

[goal view] Scroll into active goal.

---

controller/lsp_core.ml
controller/request.ml
controller/request.mli
controller/rq_completion.ml
controller/rq_completion.mli
controller/rq_definition.ml
controller/rq_definition.mli
controller/rq_document.ml
controller/rq_document.mli
controller/rq_goals.ml
controller/rq_goals.mli
controller/rq_hover.ml
controller/rq_hover.mli
controller/rq_lens.ml
controller/rq_lens.mli
controller/rq_symbols.ml
controller/rq_symbols.mli

This was long overdue and needed for #339 , now requests provider can indeed produce a failure if so they wish.

[controller] Refactoring of request interface

---

controller/doc_manager.ml
test/src/Check.test.ts
test/src/LanguageServer.ts
test/src/Lifecycle.test.ts

The process of writing this test uncovered another bug, which is separately listed as #414.

Add a test for checking entire document

---

CHANGES.md
README.md
controller/lsp_core.ml
controller/rq_save.ml
coq/save.ml
coq/save.mli
coq/workspace.mli
editor/code/lib/types.ts
editor/code/package.json
editor/code/src/client.ts
editor/code/src/config.ts
etc/doc/PROTOCOL.md
fleche/doc.ml
fleche/doc.mli

Available in both the protocol and the client.
Closes #339

[server] Add a command to save a .vo file.

---

controller/lsp_core.ml
controller/rq_goals.ml
lsp/doc.ml
lsp/doc.mli
lsp/jFleche.ml
lsp/jFleche.mli

Some small tweaks and cleanup, add common helpers.
Still we will need to have better error messages on failure.

[lsp] Refactoring of parameters parsing

---

CHANGES.md
controller/rq_hover.ml

We cleanup this code and fix the problem with notation display.
Advanced hover (like for notations) will have to wait a bit more.

[hover] Refactoring and minor fixes.

---

test/package.json
test/src/Check.test.ts

Windows CI should work fine again, c.f. #415, #423.

[test] Fix test exiting eagerly.

---

test/src/Check.test.ts
test/src/LanguageServer.ts
test/src/Lifecycle.test.ts

A more monadic style makes sense with promises, and will allow us to
capture streams of notifications etc... (and present them as async)

[test] More compositional test language

---

CHANGES.md
CONTRIBUTING.md
coq/loader.ml
editor/code/.vscode/launch.json
editor/code/esbuild.mjs
editor/code/package.json
editor/code/src/browser.ts
editor/code/src/client.ts
editor/code/src/goals.ts
editor/code/src/node.ts
editor/code/src/progress.ts

For now this will not try to start the worker.
Fixes #234

[code] Enable web extension support.

---

controller/coq_lsp.ml
coq/workspace.ml
coq/workspace.mli

This makes the API a bit more flexible for the Worker backend.
We add capability to set args from command line for example, and improve the code. Moreover we add better support for init, and support for boot.

[workspace] Refactoring and consolidation.

---

CHANGES.md
controller/rq_goals.ml

[goals] Fix goals_after_tactic option retrieval.

---

CHANGES.md
controller/rq_goals.ml
coq/state.ml
coq/state.mli
editor/code/lib/types.ts
editor/code/views/info/Info.tsx
editor/code/views/info/Loc.tsx
editor/code/views/info/Program.tsx
etc/doc/PROTOCOL.md
examples/obligations.v
fleche/info.ml
fleche/info.mli
lsp/jCoq.ml
lsp/jFleche.ml
lsp/jFleche.mli

This is a start to support hole-based programming, c.f. #192 
Works pretty well, modulo the ugly design.

[info panel] Program Obligation support in infoview

---

CHANGES.md
controller/doc_manager.ml
controller/perf.ml
controller/perf.mli
coq/ast.ml
editor/code/esbuild.mjs
editor/code/lib/types.ts
editor/code/package-lock.json
editor/code/package.json
editor/code/src/client.ts
editor/code/src/perf.ts
editor/code/tsconfig.json
editor/code/views/info/Info.tsx
editor/code/views/perf/App.css
editor/code/views/perf/App.tsx
editor/code/views/perf/index.tsx
editor/code/views/perf/media/styles.css
editor/code/views/perf/tsconfig.json
etc/doc/PROTOCOL.md
fleche/doc.ml
fleche/memo.ml
fleche/memo.mli
fleche/stats.ml
fleche/stats.mli
lsp/jFleche.ml
lsp/jFleche.mli

We will include several interesting information, such as a table with memory and time consumption, etc...
Waiting on the webview build infrastructure to finish it.

[code] [protocol] Add notification about document perf data.

---

controller/coq_lsp.ml
controller/lsp_core.ml
controller/lsp_core.mli

[lsp] Generalize LSP init loop to support async IO.

---

.github/workflows/build.yml

ci: Replace nix fmt with flake check

---

CHANGES.md
controller/coq_lsp.ml
controller/lsp_core.ml
controller/rq_init.ml
test/src/Check.test.ts
test/src/LanguageServer.ts
test/src/Lifecycle.test.ts

We now discourage any rootPath not absolute.

[lsp] [init] [workspace] Fix parsing of rootPath

---

CHANGES.md
controller/lsp_core.ml
controller/rq_goals.ml
controller/rq_goals.mli
editor/code/lib/types.ts
editor/code/src/goals.ts
etc/doc/PROTOCOL.md

This is a step to make life of clients easier, cc: @bhaktishh

[protocol] Include goal output type in goals request

---

CHANGES.md
coq/workspace.ml
coq/workspace.mli

Thanks to Arthur for the report.

[workspace] Apply warning settings from _CoqProject

---

.github/workflows/build.yml
CHANGES.md
editor/code/.prettierrc
editor/code/package-lock.json
editor/code/package.json
editor/code/src/goals.ts
editor/code/views/info/CoqPp.tsx

We update all deps but esbuild, the performance improves for jQuery can be interesting for us! Also prettier update is a bit noisy.
We also update the Typescript version.
We defer the update of esbuild to its own PR, as it requires more tweaks to work / refine.

[client] Update package.json dependencies

---

CONTRIBUTING.md

Here is some info on updating flakes.

doc: add info on updating nix flake

---

README.md

I feel the instructions are much more clear like this.

[readme] [doc] [windows] Updated README for new Coq Platform

---

CHANGES.md
compiler/driver.ml
coq/workspace.ml
test/compiler/run.t

This may be pretty useful for some users having trouble with non-standard installs.

[coq] Output findlib workspace status in workspace describe.

---

CONTRIBUTING.md
README.md

[readme] Move Nix dev instructions to the dev build.

---

README.md

In reaction to Emilio's request.

Add mention of the Coq Nix Toolbox.

---

CHANGES.md
README.md

Follow up of #572
cc: @Zimmi48 @Alizter

[README] [nix] Add changes + tweak on the README.

---

fleche/doc.ml

In preparation for user-extensible rules.

[fleche] Small refactoring on error recovery code.

---

CHANGES.md
plugins/astdump/dune
plugins/astdump/main.ml
test/compiler/proj1/a.v
test/compiler/run.t

Easy-to-use Flèche / FCC plugin to dump the AST of a file / buffer.

[plugins] AST dump plugin

---

CHANGES.md
editor/code/src/client.ts
editor/code/src/config.ts
editor/code/src/progress.ts

[code] Don't trigger goals buffer action in general Markdown documents

---

CHANGES.md
controller/lsp_core.ml
controller/request.ml
controller/request.mli
coq/dune
fleche/theory.ml
fleche/theory.mli

This should help towards a lazier checking mode.
Thanks to Julio Di Egidio and Paolo Giarruso for discussion about lazier checking.

[requests] Allow not to postpone full document requests

---

CHANGES.md
compiler/compile.ml
examples/Demo.v
plugins/README.md
plugins/goaldump/dune
plugins/goaldump/main.ml
test/compiler/run.t

This is a simple plugin that will output the Ast and goals of a document. This is just a start, there are many tweaks that could be performed indeed.
cc: @gbdrt

[plugin] Goal dump plugin.

---

examples/err_shift.v

Closes #633
Upstream PR is https://github.com/coq/coq/pull/18893

[parsing] Bump Coq to fix lexer error recovery.

---

CHANGES.md
controller/lsp_core.ml
controller/rq_selectionRange.ml
controller/rq_selectionRange.mli
etc/doc/PROTOCOL.md

[lsp] Allow `selectionRange` call to take more than one position.

---

CHANGES.md
coq/library_file.ml
coq/library_file.mli

This will be useful for petanque

[coq] Add .vo library file functions

---

CHANGES.md
CONTRIBUTING.md
README.md
compiler/compile.ml
compiler/util.mli
coq/goals.ml
coq/goals.mli
coq/library_file.ml
coq/library_file.mli
fleche/compat.ml
fleche/compat.mli
petanque/README.md
petanque/agent.ml
petanque/agent.mli
petanque/dune
petanque/test/basic_api.ml
petanque/test/dune
petanque/test/test.v

This is the first version of `petanque`, suitable for merging.
TODO before merging:

[petanque] Initial commit, as an OCaml library

---

CHANGES.md
compiler/fcc.ml
coq/args.ml
coq/args.mli
lsp/base.ml
lsp/base.mli
lsp/io.ml
lsp/io.mli
lsp/jCoq.ml
petanque/README.md
petanque/agent.ml
petanque/agent.mli
petanque/json_shell/dune
petanque/json_shell/interp.ml
petanque/json_shell/jAgent.ml
petanque/json_shell/obj_map.ml
petanque/json_shell/pet.ml
petanque/json_shell/protocol.ml
petanque/test/dune
petanque/test/json_api.ml

There are some internals that may change, but the protocol should be kinda stable unless we'd like to update it on purpose.

[petanque] Add a JSON-RPC shell

---

controller/coq_lsp.ml
lsp/io.ml
lsp/io.mli
petanque/json_shell/pet.ml

We want to handle server to client requests, so we'll need to introduce some changes.

[lsp] Rework types a bit before bigger refactoring.

---

petanque/json_shell/client.ml
petanque/json_shell/client.mli
petanque/json_shell/pet.ml
petanque/test/json_api.ml

This was used in the test, we now make it more explicit.
It will likely help at some point.

[petanque] Add an OCaml JSON-RPC petanque client.

---

CHANGES.md
editor/code/views/info/Goals.tsx
examples/goals.v

Thanks to Ali for the feedback on this cc: #525

[goals] Don't open goals levels by default.

---

petanque/json_shell/jAgent.ml

To workaround the result problem due to newer ppx_deriving

[vendor] [deps] Bump deps

---

petanque/agent.ml
petanque/agent.mli
petanque/json_shell/client.ml
petanque/json_shell/client.mli
petanque/json_shell/interp.ml
petanque/json_shell/jAgent.ml
petanque/json_shell/protocol.ml
petanque/test/basic_api.ml
petanque/test/dune
petanque/test/json_api.ml
petanque/test/json_api_failure.ml

In particular:
- we cleanup the protocol.ml file to avoid confusion
- improved return type for run_tac
- handle missing file on start
cc: @gbdrt

[petanque] Several tweaks from pet-server PR

---

CHANGES.md
editor/code/CHANGELOG.md
editor/code/package.json

Just a couple of client fixes.

[coq-lsp] Release 0.1.10

---

fleche/theory.ml

[fleche] Some minor refactorings in theory.ml

---

CHANGES.md
editor/code/src/goals.ts

Continuation / fix of #722, #725

[code] Fix focus race when a Coq file is in column 2

---

serlib/ser_uGraph.ml

Also fix merge due to problem in upstream CI.

[deps] [vendor] Bump Coq usptream

---

CHANGES.md
plugins/univdiff/dune
plugins/univdiff/main.ml

Can be used with:
```
$ dune exec -- fcc --root $absolute_path --max_errors=0 --plugin=coq-lsp.plugin.univdiff $absolute_path.v
$ cat $absolute_path.v.univdiff
```
cc: #310

[plugin] Debug plugin for printing universe deltas in files.

---

coq/goals.ml
coq/goals.mli
fleche/info.mli
lsp/jCoq.ml
petanque/agent.ml

[coq] Refactor goals type to use standard `Module_foo.t` style.

---

controller/lsp_core.ml
petanque/json_shell/client.ml
petanque/json_shell/client.mli
petanque/json_shell/interp.ml
petanque/json_shell/interp.mli
petanque/json_shell/interp_shell.ml
petanque/json_shell/interp_shell.mli
petanque/json_shell/pet.ml
petanque/json_shell/server.ml
petanque/test/json_api.ml
petanque/test/json_api_failure.ml

There was a bug in the JSON dispatch; this bug is essentially hard to catch, as it is the only time we are not typed.

[petanque] Some refactoring in interp, better types and API + fix

---

petanque/agent.ml
petanque/agent.mli
petanque/json/protocol.ml
petanque/test/basic_api.ml
petanque/test/json_api.ml
petanque/test/json_api_failure.ml

[petanque] Make `start` type more consistent with `run`

---

coq/library_file.ml
coq/parsing.ml
fleche/memo.ml

Overlay for https://github.com/coq/coq/pull/19135

[memo] Adapt to better error handling in intern upstream API

---

coq/ast.mli

To be merged synchronously with coq/coq#19075. Thanks in advance.

Adapt to Coq PR #19075: make CSet extensible

---

coq/workspace.ml
test/CoqProject/_CoqProject
test/compiler/basic/run.t
test/compiler/exit_code/run.t
test/compiler/long_file/run.t
test/serlib/genarg/extraction.v
test/serlib/genarg/libTactics.v

Adapt to https://github.com/coq/coq/pull/19310
This should be merged in sync with the upstream PR

Adapt to https://github.com/coq/coq/pull/19310

---

CHANGES.md
coq/ast.ml
examples/rewrite/_CoqProject
examples/rewrite/simple.v

[coq] Understand rewrite rules and symbols on document outline

---

CHANGES.md
coq/ast.ml
coq/ast.mli
examples/MetaCommands.v
fleche/doc.ml

Thanks to Ali for pointing this out.
Fixes #827

[coq] [fleche] Support `Restart` command.

---

compiler/driver.ml
controller/coq_lsp.ml
coq/init.ml
coq/init.mli
petanque/json_shell/shell.ml

Taken from #433, it is very useful there to run with a disabled VM.

[coq] [init] Allow init to tweak VM mode and warnings.

---

CHANGES.md
petanque/agent.ml
petanque/test/basic_api.ml
petanque/test/test.v

[petanque] Fix bug for detection of proof finished in deep stacks

---

.github/workflows/build.yml
test/server/src/Check.test.ts

Also, we tweak a bit the order on tests, but indeed we still have a race, need to improve that.

[vendor] Bump Coq

---

.github/workflows/build.yml
.gitmodules
CHANGES.md
Makefile
controller-js/dune

We need also to bump setup-ocaml action due to unrelated CI brokeness :/
This replaces https://github.com/ejgallego/coq-lsp/pull/815

[build] Adapt to Rocq stdlib split + fix setup-ocaml CI

---

.github/workflows/build.yml
Makefile
coq/workspace.ml
petanque/README.md
petanque/test/dune
test/compiler/basic/dune
test/compiler/basic/run.t
test/compiler/exit_code/dune
test/compiler/exit_code/run.t
test/compiler/long_file/dune
test/compiler/long_file/run.t
test/serlib/genarg/dune

We also fix missing test suite deps which are more obvious now.

[misc] [ci] [windows] Some more nits form Rocq / Coq migration

---

CHANGES.md
petanque/agent.ml
petanque/test/basic_api.ml
petanque/test/test.v

[petanque] Fix `petanque/start` when a theorem is parsed but has errors

---

.github/workflows/build.yml
coq-lsp.opam

https://github.com/ocaml/opam-repository/pull/27253 was merged

[ci] Use fixed ocamlfind package in Windows CI

---

.gitmodules
CHANGES.md
Makefile
controller-js/dune
etc/0001-engine-trampoline.patch
examples/waterproof_test.v
vendor/README.md

[build] [js] Add coq-waterproof to JS build.

---

CHANGES.md
editor/code/src/browser.ts

Reported by @amblafont, thanks!
Fixes #877

[vscode] [web] Fix web extension not exporting the coq-lsp API

---

Makefile

[ci] [web worker] Build Web Worker with patched Coq in stable versions.

---

CHANGES.md
coq/args.ml
coq/args.mli
petanque/json_shell/shell.ml

We tweak the patch a little bit, and note the change in the changelog as it is user observable.

[vendor] Bump Coq submodules after #891

---

.github/workflows/build.yml
Makefile

[js] [deps] Bundle WaterProof 2.2.0+8.20 in JS build

---

CHANGES.md
controller/rq_hover.ml
coq/state.ml
editor/code/package.json
editor/code/src/config.ts
fleche/config.ml

[hover] New hover display and option `show_state_hash_on_hover`

---

CHANGES.md
controller/lsp_core.ml
controller/request.ml
controller/request.mli
controller/rq_definition.ml
controller/rq_goals.ml
controller/rq_hover.ml
controller/rq_save.ml
etc/doc/PROTOCOL.md
fleche/doc.ml
fleche/doc.mli
fleche/info.ml
fleche/io.ml
fleche/io.mli
lsp/base.ml
lsp/base.mli
lsp/jFleche.ml
lsp/jFleche.mli
petanque/json_shell/interp_shell.ml

This is basically the 2nd part of #961, which left a few things not properly done, as discovered when writing #960

[fleche] [lsp] Uniformize feedback type with message, bugfixes for #961

---

lsp/base.ml
lsp/base.mli
petanque/agent.ml
petanque/agent.mli
petanque/json/protocol.ml
petanque/test/json_api.ml

We add a test, and make the type use the LSP standard `Position` type.

[petanque] Improve type for get_state_at_pos, add a test

---

CHANGES.md
README.md
etc/doc/PROTOCOL.md
fleche/info.mli

Many thanks to Josselin Poiret !
cc: #941
@jpoiret @arthuraa are you Ok with this change?

[doc] Some improvements to `proof/goals` doc, emacs link.

---

CHANGES.md
plugins/count_genargs/dune
plugins/count_genargs/main.ml
serlib/ser_genarg.ml
serlib/ser_genarg.mli

This is a first step towards more interesting AST analysis.

[serlib] Support for generic Ast analyzers

---

CHANGES.md
coq/workspace.ml
etc/doc/USER_MANUAL.md

[fleche] Support _RocqProject

---

CHANGES.md
CONTRIBUTING.md
controller/rq_completion.ml
controller/rq_goals.ml
controller/unicode_bindings.ml
editor/code/package.json
editor/code/src/config.ts
etc/doc/PROTOCOL.md
fleche/config.ml
lsp/jFleche.ml

Reverts ejgallego/coq-lsp#999
Merged in mistake

Revert "[lsp] Return executed sentence info in goal request."

---

CHANGES.md
coq/ast.ml
examples/documentSymbol.v
serlib/plugins/ltac/ser_tacexpr.ml
serlib/ser_analysis.ml

This is a showcase for the new analysis infra; just a proof of concept, but seems to work!
Fixes #632

[coq] [serlib] Ast analysis / outline for Notation, Ltac, and Tactic Notation
