ejgallego/rocq-lsp

- controller/coq_doc.ml
- controller/coq_lsp.ml
- controller/dune
- controller/memo.ml
- lsp/debug.ml
- lsp/dune
- lsp/io.ml
This is the result of today's hacking jointly with Ali, just an experiment, but includes
an optimization that is useful to avoid repeated checking.
A couple other commits also pushed.
> [lsp] Implement event loop processing Thread

- controller/coq_doc.ml
I think that's the correct thing to do, as we don't want to continue
as of now with error recovery, etc...
> [fleche] When interrupted in parsing, signal end of file

- CHANGES.md
- controller/coq_doc.ml
- controller/coq_doc.mli
- controller/coq_interp.ml
- controller/coq_interp.mli
- controller/coq_lsp.ml
- controller/memo.ml
- controller/memo.mli
Goal printing is dependent on the state, thus it makes sense to cache
it, as otherwise we'd have to restore the state to print them, which
would kind of defeat the purpose of caching.
This fixes a bug when we'd print goals in the wrong state as `Memo`
wouldn't set the state correctly.
Feedbacks are not, per-se, dependent on the state, but we cache them
too as it makes sense to modularize the code that way.
> [interp] Cache goals and feedbacks in the interpretation cache.

- CHANGES.md
- controller/coq_protect.ml
- controller/coq_protect.mli
- controller/memo.ml
This makes the cache much more efficient, with now almost perfect hit
rate.
However, this also makes obvious the problem we have with our caching
system as indeed located messages (and diagnostics) are unsound
w.r.t. to location-independent caching.
We must implement a proper fix to this strategy before merging this; I
think we can indeed make the cache aware of the location a command was
cached, and thus include the offset when we get a hit, and adjust
the cached messages accordingly. Exciting!
> [serapi] Bump to version that implements hash / compare for tactics.

- dune
This stops things like ocamlformat or compiler warnings from being checked in the vendored directories.
ps-id: 7a8b280a-bc4d-45e2-a966-b28eddb2fde8
> mark vendor/ as vendored_subdir for Dune

- fleche/config.ml
- fleche/doc.ml
- fleche/stats.mli
Thanks to Pierre-Marie Pédrot for the suggestion.
c.f. https://github.com/coq/coq/issues/11994
> [stats] Add quick memory stats to sentence information.

- fleche/doc.ml
Given that we do all the work, we may as well give a bit more feedback to the user. Inspired by the discussion on Lean 4 progress notification issue.
> [diags] Send processing diagnostics if in eager mode.

- CHANGES.md
- README.md
- controller/coq_lsp.ml
- coq/goals.ml
- coq/goals.mli
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/goals.ts
- fleche/debug.ml
- media/styles.css
Activated using Alt+Enter; needs improvement.
> [vscode] Implement Goal Command

- README.md
- controller/coq_lsp.ml
- controller/dune
- editor/code/package.json
- editor/code/src/client.ts
- fleche/config.ml
- fleche/doc.ml
- lsp/base.ml
- lsp/base.mli
- lsp/io.ml
This is very convenient as for the user to be able to set server options that currently require a recompile.
> [lsp] Support client-side setting of server options.

- fleche/info.ml
That was an oversight from when we didn't have the `in_state` API.
> [goal] Fix goal printing to happen in the right state.

- .github/workflows/build.yml
- Makefile
- flake.nix
This gives a faster lint job and allow the flake to follow the version of ocamlformat seamlessly.
> chore: Nix detects .ocamlformat version + CI fmt uses Nix

- CHANGES.md
- README.md
- controller/coq_lsp.ml
- editor/code/src/client.ts
- lsp/base.ml
- lsp/io.ml
- lsp/io.mli
- lsp/log.ml
- lsp/log.mli
We implement client-side logging (using LSP protocol), and in particular, we use it to warn the user the heavy-duty log file couldn't be created.
This should solve problems some users were having due to permissions errors.
> [lsp] Implement LSP client-side logging, don't crash on log file creation

- CHANGES.md
- controller/coq_lsp.ml
- coq/init.ml
- coq/init.mli
- coq/workspace.ml
- coq/workspace.mli
- editor/code/src/client.ts
- fleche/doc.ml
- fleche/doc.mli
We improve our handling of workspaces, preparing the way to setup workspace from `dune` files.
We now log to the user useful workspace detection information, and we read from `_CoqProject` plugin paths, which should likely solve the problems some users were seeing with their plugin-developments not working.
> [lsp] Improve workspace detection and logging.

- README.md
It is not sfficient for `coq-lsp` to be in $PATH when developing.
> README: remove bogus instruction

- CHANGES.md
- fleche/doc.ml
- fleche/doc.mli
This makes a lot of difference in the regular mode for large documents. We now go from O(n*d) to O(d^2) where n is the number of sentences and d is the number of diagnostics.
> [eager diagnostics] Only send diagnostics when they have changed

- CHANGES.md
- controller/coq_lsp.ml
- coq/state.ml
- fleche/doc.ml
- fleche/info.ml
- fleche/info.mli
We now resume document checking from the point it was left at. That
required some fixing upstream, see https://github.com/coq/coq/pull/16978 .
It seems to work well and be simple enough.
This does stress `Coq.State.compare`, so I did implement a much weaker
version; unfortunately we don't have a test-suite for checking that
memo is working properly, so we need to keep an eye on it and do some
manual testing.
> [fleche] Resumption of document checking

- controller/coq_lsp.ml
- coq/ast.ml
- coq/ast.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/info.ml
- fleche/info.mli
We rework the document definition so now every span of the document that we process will have a node, even if an Ast can't be produced.
This makes more sense and allows us to store the diagnostics per-node; moreover, unparseable bits have now an associated node, which is important for completion and other use cases such as common prefix handling.
> [fleche] Store diagnostics per node, create nodes for unparseable spans

- CHANGES.md
- controller/coq_lsp.ml
- editor/code/package.json
- fleche/config.ml
We stop displaying messages such as "Foo is defined" as feedback by default; users willing to see them can set the corresponding option.
Closes #108
> [diagnostics] Don't convert Coq "Info" messages to feedbacks

- CHANGES.md
- README.md
- controller/coq_lsp.ml
- editor/code/package-lock.json
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/goals.ts
- editor/code/src/progress.ts
- etc/doc/PROTOCOL.md
- fleche/debug.ml
- fleche/doc.ml
- fleche/doc.mli
- fleche/info.ml
- fleche/io.ml
- fleche/io.mli
- fleche/types.ml
- fleche/types.mli
- lsp/base.ml
This is modelled after Lean's `$/lean/fileProgress` notification: a
yellow bar in the right side panel indicates what parts of the
document are still not checked.
Fixes #54
Note that we send on fileProgress per sentence, that's likely too
much; for now, we throttle the decoration update. Could be made into a
user-config.
> [check] Implement `fileProgress` notification for document progress

- CHANGES.md
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/goals.ts
We allow to show goals on click, on cursor movement, or on both. User-configurable.
Fixes #89
> [goals] Show goals on click (+ configuration options).

- CHANGES.md
- fleche/doc.ml
This does greatly reduce latency when editing deep down in a
document; closes #110 .
Also, kind of makes the need for parsing caching (#25, #36) moot, at
least with the current checking workflow.
> [fleche] Resume checking from common prefix on new version.

- CHANGES.md
- controller/coq_lsp.ml
- fleche/info.ml
- fleche/info.mli
- lsp/base.ml
- lsp/base.mli
In particular, for hover and goals we check we have reached the right position, for `documentSymbol` we wait for the document to be fully checked.
Fixes #100
> [lsp] Only serve request when the document meta-data is up to date.

- CHANGES.md
- README.md
- controller/coq_lsp.ml
- editor/code/CHANGELOG.md
- editor/code/src/client.ts
- fleche/config.ml
For now we don't keep backwards compatibility on the custom protocol stuff and options.
> [init] Check that the client and server version do match.

- controller/coq_lsp.ml
- etc/doc/PROTOCOL.md
Extracted from #141 as not to block other works.
This will make the changes in #136 to use `find_opt` much easier.
> [controller] Refactor document handling

- CHANGES.md
- controller/coq_lsp.ml
I've removed it from the debug.ml file since it makes it awkward to turn on from there.
> feature: add --bt flag

- Makefile
This makes it convenient to install the extension whilst developing.
> makefile: add extension target

- CHANGES.md
- controller/coq_lsp.ml
- coq/init.ml
- coq/init.mli
- coq/workspace.ml
- coq/workspace.mli
- fleche/doc.ml
We rework the workspace code to be more principle and in line with what it is done in other tools.
This fixes a bug with `no_init` and makes HoTT to work (except for already known bugs)
Closes #138
> [coq] Workspace handling code rework

- CHANGES.md
- controller/coq_lsp.ml
- coq/workspace.ml
- coq/workspace.mli
Some tweaks left out of #150 by mistake.
> [coq] Workspace handling code rework, part 2

- CHANGES.md
- coq/state.ml
- coq/state.mli
- editor/code/package.json
- editor/code/src/client.ts
- fleche/config.ml
- fleche/doc.ml
- fleche/memo.ml
- fleche/memo.mli
This can be pretty helpful in order to have a better development workflow.
We provide an option so the user can control it.
TODO: We need to better integrate error recovery with the Memo cache, as of now, we re-admit every time so memo won't see the state post-`Qed` is the same.
Fixes #90
> [error recovery] Allow to admit proofs on failed `Qed`.

- controller/coq_lsp.ml
- coq/protect.ml
- coq/protect.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/memo.ml
`Coq.Init` will actually often `Require` Coq's prelude and perform arbitrary actions, we now reflect this on the type.
We still have a way to improve here, but for now the code is clear and the server should not crash anymore unless there is a real bug in `coq-lsp`.
Closes #91
> [fleche] Protect Coq document creation

- CHANGES.md
- controller/coq_lsp.ml
- coq/init.ml
- coq/init.mli
- coq/interp.ml
- coq/parsing.ml
- coq/parsing.mli
- coq/print.ml
- coq/print.mli
- coq/protect.ml
- coq/protect.mli
- coq/state.ml
- coq/state.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/info.ml
Work on tricky issues made me realize that we don't handle anomalies
and Coq errors still in the best way, thus https://github.com/ejgallego/coq-lsp/issues/91 is not really solved.
There are 2 issues this PR solves:
- goal printing can raise an anomalies and errors, due
to setting state and printing,
- it is safer to stop checking and set the document to failed when an
anomaly happens (tho we could make this configurable).
Thus, we go full principled in terms of API and make `Protect`
mandatory on the exported APIs from `coq` library.
We also introduce a `Failed` state that prevents further checking of
that document without having finished it.
Really fixes https://github.com/ejgallego/coq-lsp/issues/91, and a step towards https://github.com/ejgallego/coq-lsp/issues/153
TODO: protect calls …
> [coq] Protect all base API calls

- controller/coq_lsp.ml
- lsp/base.ml
- lsp/base.mli
This was long overdue, so we can now start to handle better some critical stuff, such as request cancellation, proper LSP initialization sequence, and principled request response (both immediate and delayed).
> [controller] Separate dispatching of notifications and requests

- CHANGES.md
- controller/coq_lsp.ml
- coq/workspace.ml
To that extent we introduce a special init loop for server initialization.
See: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize
> [controller] Follow the initialize specification better.

- CHANGES.md
- editor/code/package.json
- editor/code/src/client.ts
Fixes #163
This makes VsCodeVim cursor tracking work; thanks to Cactus (Anton) Golov for detailed bug reporting and testing.
> [code] Allow goals to follow selection update by a command

- CHANGES.md
- controller/coq_lsp.ml
- controller/doc_manager.ml
- controller/doc_manager.mli
- controller/requests.ml
- controller/requests.mli
Some requests need to be delayed until the document is ready, such as
`documentSymbols`. In order to do this, we allow to postpone requests,
and `Doc_manager.check` will now return the list of requests pending
for a given document.
The implementation is lightweight and quite a prototype, but should
serve as a basis for more advanced stuff.
Closes #124.
> [controller] Allow to postpone and cancel requests

- CHANGES.md
- controller/coq_lsp.ml
- controller/doc_manager.ml
- controller/doc_manager.mli
- controller/requests.ml
- controller/requests.mli
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/goals.ts
- fleche/debug.ml
- fleche/doc.ml
- fleche/doc.mli
- lsp/base.ml
This provides a much nicer typing and navigation experience, basically if some data about the document is not ready, the request is postponed and will be served when such data becames available.
We also switch the default for the client as to show goals on typing / movement of the cursor. With the new delay capability, this gives the user usually what they want in terms of the goal panel being up-to-date.
Some notes:
- For now we only postpone goal requests, we should implement a proper queue (in next PRs). One pending goal request works pretty well for interactive use.
- `Doc.Target.t` can be more refined, as to support `Info.find` `Prev` behavior (but this is a bit complex due to the way both searches interact)
> [controller] Postpone position requests until doc checking catches up.

- CHANGES.md
- editor/code/package.json
The keybinding alt+enter is also used in find-and-replace, when the user wants to replace all instances. Before this change, the keybinding supplied by coq-lsp used to interfere. Moreover, the keybinding should be scoped for just the coq language.
> editor/code: scope keybinding alt+enter correctly

- fleche/doc.ml
- fleche/doc.mli
- fleche/types.mli
This is both a cleanup, and a essential feature so we can convert byte offsets to unicode character points, thus adding Unicode support to `coq-lsp`.
> [fleche] Cache computation of contents structure and processing

- editor/code/esbuild.mjs
- editor/code/package.json
- editor/code/src/client.ts
Otherwise it doesn't work. We configure our build setup for the esbuild VSCode matcher.
We also consolidate the output directory under `out`.
Fixes #203
> [esbuild] Properly detect --watch --sourcemap=no and --minify parameters

- CHANGES.md
- README.md
- controller/coq_lsp.ml
- editor/code/package.json
- lsp/base.ml
- lsp/base.mli
This argument was introduced very long time ago in the Lambdapi implementation as we were not fully LSP compliant, but now we are.
The argument itself has been disabled since a long time, and it misleading now; moreover we put it as default in `package.json`!!!
> [lsp] Remove noop --std argument.

- editor/code/.vscodeignore
- editor/code/esbuild.mjs
This was still not working properly, now it does. We also exclude `.tsbuildinfo` files which are bulky and not useful.
> [code] [build] Don't include sourcemaps in marketplace package

- .github/workflows/build.yml
- Makefile
- editor/code/src/client.ts
Recent changes to our setup meant that compile is not type checking anymore, thus CI didn't catch a type error that broke the extension.
We now test the release build in CI then, and maybe we could even compare the output of `ls` to a set of files, and add some more checks.
Thus, `make extension` is now really a "release" target.
(I don't want to make CI use `make`, but the default build driver for
the VSCode marketplace)
> [build] [code] [ci] Check TS compilation on CI.

- CHANGES.md
- editor/code/package.json
We group settings into related categories.
> categorize settings

- editor/code/package.json
This changes the settings entry of the extension from "coq-lsp" to "Coq LSP" which is how we describe the extension in vernacular language.
> change displayName to Coq LSP

- controller/coq_lsp.ml
- controller/doc_manager.ml
- controller/doc_manager.mli
This will help to make this module independent of the particular event system chosen, that will help with the jsCoq port too.
> [doc manager] Remove [yield] from [Doc_manager.check]

- controller/coq_lsp.ml
- coq/workspace.ml
- coq/workspace.mli
This allow us to enable backtraces from the `initialize` request.
We will keep the backtrace flags / option as this is the only way to get backtraces of the early init process, which is often needed.
> [workspace] Allow to enable backtraces on a workspace-basis

- controller/coq_lsp.ml
- controller/doc_manager.ml
- controller/dune
- controller/requests.ml
- controller/rq_init.ml
- fleche/doc.ml
- fleche/io.ml
- fleche/io.mli
- fleche/progress.ml
- fleche/types.ml
- fleche/types.mli
- lsp/base.ml
- lsp/base.mli
- lsp/dune
- lsp/io.ml
- lsp/jFleche.ml
- lsp/jFleche.mli
We can do much better, but we will need to introduce the Lang library first. For now, we remove the ppx yojson and import from the controller, and consolidate some types.
Attention to the `extra` stuff in diagnostics, we may need to reintroduce the --std flag.
cc: #2
> [lsp] Cleanup LSP stuff, improve static typing.

- CHANGES.md
- controller/coq_lsp.ml
- coq/workspace.ml
- coq/workspace.mli
This is needed in quite a few cases, thus a fix.
> [workspace] use `rootPath` to detect `_CoqProject` file.

- CHANGES.md
- controller/rq_completion.ml
- fleche/utf8.ml
We were returning as the index the length of the line, which is actually out-of-bounds, should be 0 or `length line - 1` as to be a proper argument to `String.get`.
We also improve the validation for the line number in the request.
Fixes #264
> [completion] Return last valid index when request is out-of-bounds

- controller/rq_completion.ml
- fleche/coq_utils.ml
- fleche/doc.ml
- fleche/utf8.ml
- fleche/utf8.mli
We are now more strict, and require the [Utf8] clients to take an action when the conversion fails.
Usually clients doing the conversion for the range will want to select the total length (last character) whereas the clients trying to grab a character will want to abort whatever they are doing.
I have reviewed all such uses, and found a couple of errors.
This also fixes the bug with the `fileProgress` range due to the above.
Re Fixes #264
> [doc] [completion] Improve UTF-8 and position validation

- CHANGES.md
- lsp/jFleche.ml
As in diagnostics, LSP ranges don't include Flèche's offset field.
While this is not enforced in VS Code, we fix that to remain within the LSP standard.
This problem was introduced in #254
> [lsp] Make sure ranges are serialized to LSP types

- controller/coq_lsp.ml
- controller/coq_lsp.mli
- controller/dune
- controller/lsp_core.ml
- controller/lsp_core.mli
- lsp/io.ml
- lsp/io.mli
This is a pre-requisite to implementing the `coq-lsp` Web Worker natively.
> [controller] Move platform-independent bits to controller library.

- CHANGES.md
- README.md
- examples/lists.mv
- fleche/doc.ml
- fleche/doc.mli
This is needed for some multi-lang documents.
> [fleche] [markdown] Require Coq markdown snippets to use ```coq

- CHANGES.md
- controller/lsp_core.ml
- controller/rq_init.ml
- controller/rq_init.mli
> [lsq_init] `rootPath` is optional, `rootUri` has precedence.

- CHANGES.md
- README.md
- controller/doc_manager.ml
- controller/lsp_core.ml
- fleche/doc.ml
- fleche/doc.mli
Fixes #275 , fixes #281 
We use a heuristic in the fixed up branches as follows: if the Coq version contains LSP, then we assume the fix has been backported.
That should work when doing `opam pin`.
> [fleche] Reject opening multiple Coq documents for buggy Coq versions.

- CHANGES.md
- lsp/jFleche.ml
Yojson ppx doesn't work too well for this kind of enumeration types (they are serialized to a list with a string)
This was broken by #254
> [server] [lsp] Fix bug when parsing client option for unicode completion

- CHANGES.md
- editor/code/package.json
- editor/code/src/config.ts
- fleche/config.ml
- fleche/doc.ml
- lang/diagnostic.ml
- lang/diagnostic.mli
When this happens, it is because usually the Coq install or workspace is in a bad state, or some other fatal problem, so no point in overflowing the clients with diagnostics.
For now I've settled with a default limit of 150 max errors per file.
> [fleche] Stop checking a document when there are too many errors.

- CHANGES.md
- coq-lsp.opam
- coq/dune
- coq/workspace.ml
Remove ad-hoc handling of uri, and use the Uri module instead. This gives us the benefit of being able to percent-decode, and support unicode filenames.
> workspace: support unicode filenames

- editor/code/CHANGELOG.md
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/progress.ts
- editor/code/syntaxes/coqmarkdown.json
- editor/code/syntaxes/markdown-coq-codeblock.json
Make `.mv` files inherit markdown grammar and inject coq grammar into coq codeblocks in both `.mv` and `.md` files.
> [code] Improve markdown syntax highglighting

- CHANGES.md
- editor/code/src/goals.ts
Fix https://github.com/ejgallego/coq-lsp/issues/305
Tested and works.
> Enable find widget in goal panel

- CHANGES.md
- editor/code/views/info/CoqPp.tsx
- editor/code/views/info/Details.tsx
- editor/code/views/info/Goals.tsx
- editor/code/views/info/media/coqpp.css
- editor/code/views/info/media/goals.css
- examples/goals.v
- lsp/jCoq.ml
- lsp/jFleche.ml
- lsp/jFleche.mli
This is an adaptation to React of the jsCoq goal printing code, but
our current model is a bit different so actually the code is not the
same.
In particular, we display bullets goals, and a bunch of extra
information, including goal preview.
Fixes #288
This is inspired by code originally written by Shachar Itzhaky.
> [goals] Adapt jsCoq goal printing code to VS Code / React

- CHANGES.md
- controller/lsp_core.ml
- controller/requests.ml
- controller/requests.mli
- controller/rq_completion.ml
- controller/rq_symbols.ml
- controller/rq_symbols.mli
- coq/ast.ml
- coq/ast.mli
- examples/documentSymbol.v
- examples/ex0.v
- fleche/doc.ml
- fleche/doc.mli
- lsp/jFleche.ml
- lsp/jFleche.mli
Fixes #121, #122
We improved `documentSymbol` return type for the newer `DocumentSymbol[]` hierarchical symbol support in recent LSP versions.
Sections and modules will now be properly represented, as well as constructors for inductive types, projections for records, etc...
> [info] Improve `documentSymbol` request to return extended info.

- .gitignore
- CONTRIBUTING.md
- flake.nix
We add `nodejs` to the main flake, since that is all that is needed to build the extension. There is also a vscode dev shell but that pulls in extra stuff like the type script language server.
I also document a workflow where you can save the configuration of `nix develop` in a profile and add a standard place for people to store their profiles to git ignore.
> [Nix] add nodejs to flake and ignore nix/profiles directory

- CHANGES.md
- controller/coq_lsp.ml
- controller/lsp_core.ml
- controller/lsp_core.mli
- controller/rq_init.ml
- controller/rq_init.mli
- lsp/workspace.ml
- lsp/workspace.mli
This is very useful in projects with several `_CoqProject` files.
> [lsp] [controller] Add support for workspace folders

- lsp/base.ml
Problem found by Ramkumar, indeed the `exit` and `shutdown` RPC calls do have `params` missing.
> [lsp] Fix bug on request / notification parsing

- CHANGES.md
- controller/coq_lsp.ml
- controller/lsp_core.ml
- editor/code/package-lock.json
- lsp/io.ml
- lsp/io.mli
Problem found by Ramkumar, great job!
Indeed I think we never had the right code handling this, as observed
in many instances when the server complained about a forced shutdown.
Likely fixes #230
Co-authored-by: Ramkumar Ramachandra <r@artagnon.com>
> [controller] Fix bug where the controller was not exiting

- CHANGES.md
- editor/code/package.json
- editor/code/src/config.ts
- fleche/config.ml
- fleche/doc.ml
Since the introduction of #106, this feature is redundant, and only serves to choke up notifications in VSCode.
> fleche, editor: strip Ok_diagnostic feature

- controller/cache.ml
- coq/interp.ml
- coq/interp.mli
- coq/workspace.ml
- coq/workspace.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/memo.ml
- fleche/memo.mli
- lang/lUri.ml
- lang/lUri.mli
Some clients, such as Visual Studio Code, may open / close buffers
aggressively when working, this creates some extra load as we don't
cache document creation.
This PR does cache it. In general this has a very low footprint on
memory by itself, as the root state is shared across all buffers, but
of course, the documents themselves could be a big load, but that's
already the case so we don't make things worse.
Fixes #363
[Test suite passes ;)]
> [fleche] Cache document creation

- CHANGES.md
- controller/rq_common.ml
Actually we should return a set of candidates, but this provides better results.
> [nit] Scan also identifiers with doc, Coq's "qualids"

- CHANGES.md
- coq/protect.ml
If an exception is raised after an `unfreeze_interp_state`, the cache will be invalid.
Thanks to @r-muhairi for help in identifying this problem.
> [coq] Invalidate vernacstate cache on exception

- CHANGES.md
- controller/coq_lsp.ml
- coq/workspace.ml
- coq/workspace.mli
This is in line with upstream Coq; we also add the `--coqcorelib` command line option.
We still don't support the `coq_environment.txt` hack, as it relies in `Sys.executable_name` which seems very very fishy.
> [coq] [workspace] [init] Recognize COQLIB and COQCORELIB

- CHANGES.md
- editor/code/src/client.ts
Clicking on it will try to restart the server which is IMO a good thing.
Fixes #399
> [client]  Server status icon will now react properly to fatal server errors

- CHANGES.md
- controller/rq_hover.ml
- editor/code/package.json
- editor/code/src/config.ts
- fleche/config.ml
Set the new option `coq-lsp.stats_on_hover_option` to re-enable
it.
Fixes #398
> [hover] Info on memory and time is now disabled by default

- controller/doc_manager.ml
> doc_manager: diagnostic with severity 0 is forbidden by lsp

- CHANGES.md
- README.md
- coq/loader.ml
This was the wrong thing to do, I was just lazy.
We should refactor the loader so it works in a different and doesn't depend on the hardcoded list.
This means we relax the SerAPI deps for 8.16
> [loader] Don't fail on missing serlib plugins

- .github/workflows/build.yml
The problem was introduced in #415
We also set a timeout as a safeguard vs future problems.
> [ci] Disable windows test until we can figure out the problem.

- Makefile
See https://github.com/coq/coq/pull/17289 for more details.
> [build] Set libdir explicitly in configure, to workaround configure bug.

- controller/coq_lsp.ml
- controller/doc_manager.ml
- controller/doc_manager.mli
- controller/lsp_core.ml
- controller/lsp_core.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/io.ml
- fleche/io.mli
- lsp/io.ml
- lsp/io.mli
Turns out the transport layer for the worker case is directly over JS objects, we thus generalize the IO types accordingly to prepare for the worker version of coq-lsp.
> [io] Abstract IO functions

- controller/coq_lsp.ml
- controller/lsp_core.ml
- controller/lsp_core.mli
So we can reuse this code in the worker version.
We thus update the interface of Core, all that remains to see if we
can reify the two loops too.
We are basically doing algebraic effects, which can mean we may be going in the right direction for newer OCaml actually, that was not on purpose.
> [controller] Reify yield action in the queue controller.

- CONTRIBUTING.md
Did a pass on the contributing guide:
- Rewrote the sections on compiling/setting the client as a step-by-step guide (mainly added list of steps)
- Split the Nix sections between the server and client (it was all inside the server guide)
- Added a bit more instructions on setting the client with Nix 
- Moved the `releasing` section outside the server guide
> doc: Restructure contributing guide (server+client guides)

- CHANGES.md
- coq/workspace.ml
It was printing the wrong file, reported by Alex Sanchez-Stern.
> [workspace] Fix message about workspace detection

- controller/coq_lsp.ml
- coq/init.ml
- coq/init.mli
This is unnecessary as init can hook directly with protect, and should. No need to expose this internal detail.
This will simplify the setup in #433 (and other clients)
> [coq] Don't expose feedback to clients.

- CHANGES.md
- controller/lsp_core.ml
- controller/rq_init.ml
- lsp/io.ml
- lsp/io.mli
Workspace parsing must accept `null` as per LSP.
Beware we still require the invariant that at least one workspace is returned by init, we should maybe drop that at some point.
Thanks to orilahav for reporting and debugging this issue.
Fixes #283
> [init] Be more resilient to input, fix bug on workspace parsing

- CHANGES.md
- editor/code/package.json
The shortcut for the goals command is broken since VS Code doesn't allow parentheses in key binding `when` clauses.
> [code] Fix goals command keybind

- .gitattributes
This allows GitHub to correctly detect the lanugage for a given file extension. At the time, some .ml files were being classified as standard ml.
> meta: add .gitattributes file

- controller/doc_manager.ml
- controller/doc_manager.mli
- controller/lsp_core.ml
- controller/request.ml
- controller/request.mli
Document manager is the current owner of the build state, so it makes sense that it is the component to decide whether a (data) request should be postponed.
This fixes two code todos (`AbortRequest` and duplication of checks) and should open the way for a deeper refactoring of `Doc_manager` towards a true build system for a set of documents.
> [doc manager] Move postponement logic to document manager.

- editor/code/src/goals.ts
ViZX can be found [here](https://marketplace.visualstudio.com/items?itemName=inQWIRE.vizx). I just added code to execute a ViZX command when the extension is active; the goal is to enrich some textual goal display with a visualization; this command will simply open a webview with the visualization. ViZX has to be installed and active for the command to be executed; the goals object is the only information passed to ViZX.
> Added required support for ViZX Extension

- editor/code/src/goals.ts
- editor/code/views/info/ErrorBrowser.tsx
- editor/code/views/info/Info.tsx
- editor/code/views/info/index.tsx
- editor/code/views/info/media/index.css
- editor/code/views/info/media/info.css
Addresses #441. 
The error panel uses as much space as possible (might be missing some overflow style?) whenever there are errors. The goals panel has scrolling in case it gets smushed.
There is still an issue with `scrollIntoView` which makes the panel flicker in general and it might still be missing a top padding (#435). 
Lmk what you think (the gif below is clipped at the bottom but it's displaying ok in the editor).
> [code] ui: Add divider between errors and goals (#441)

- CHANGES.md
- controller/coq_lsp.ml
New command line argument `--idle-delay=$secs` that controls how much an idle server will sleep before going back to request processing.
Default setting is `0.1`, using more aggressive
settings like `0.01` can decrease latency of requests by ~4x.
Replaces #467.
> [controller] [native] New parameter --idle-delay

- CHANGES.md
- lsp/jCoq.ml
As seen in
https://coq.zulipchat.com/#narrow/stream/329642-coq-lsp/topic/coq.2FgetDocument.20error we don't want to error when we can't serialize some Ast properly, but instead provide a fallback.
Doing this properly requires `Serlib_base` to expose the exception, we use the hack for now until we can bump the `serlib` dep.
> [getDocument] Be more resilient on unknown ASTs

- CHANGES.md
- coq/dune
This has been possible since some time in Coq `master`
> [coq] Don't link the STM

- fleche/doc.ml
- fleche/doc.mli
- fleche/theory.ml
Closes #506
Note the change of semantics for the document diagnostics modification, before we relied on `Theory` sending the diags on stop, we now properly send them as a part of eager diagnostics.
> [fleche] Add preliminary Document Completion hook

- CHANGES.md
- README.md
- editor/code/views/info/Info.tsx
- editor/code/views/info/Message.tsx
- editor/code/views/info/Messages.tsx
We limit the number of messages displayed in the goal window to 101, to workaround slow render of Coq's pretty printing format.
This is an issue for example in Search where we can get thousand of results.
We also speed up the rendering a bit by not hashing twice, and fix a parameter-passing bug.
Thanks to Anton Podkopaev for reporting.
> [vscode] Limit the number of messages displayed in the goal window

- Makefile
- test/compiler/dune
- test/compiler/run.t
We stop using makefile hacks and set the test sanitization in the `run.t` file, and the plugin deps in the `dune` file.
> [build] [test] Fix CRAM tests on OPAM files

- CHANGES.md
- controller/lsp_core.ml
- lsp/doc.ml
That made the `coq/saveVo` fail with an invalid parsing error.
The issue was that when we handle generically the requests that need to wait for the document to be completed, we were retrieving the `uri` parameter using the de-serializer for the `TextDocumentIdentifier` data-type, however both `coq/getDocument` and `coq/saveVo` use `VersionedTextDocumentIdentifier`.
As the JSON parser finds this extra param, it fails. We solve this making the parser in this case no strict, but further hardening is needed at this level.
Thanks to Théo Zimmerman for the report and help with debugging this issue.
> [lsp] Fix bug when retrieving URIs from document params

- CHANGES.md
- editor/code/views/info/media/coqpp.css
> Color changes for light color themes.

- .github/workflows/build.yml
- Makefile
Reverts #423 , the problem was due to us executing the tests natively from the Windows Powershell (as we want things to run), however we did set the path to a Cygwin-style one which didn't work from Powershell.
Closes #424 cc: #1 #481
> [ci] Fix test suite on Windows

- CONTRIBUTING.md
- README.md
Update to reflect that we have had stable Nix packages for a while.
> [doc] [nix] [readme] Update Nix documentation

- CHANGES.md
- compiler/args.ml
- compiler/driver.ml
- compiler/fcc.ml
`fcc` now understands the `--coqlib`, `--coqcorelib`, `--ocamlpath`, '-Q`, and `-R` arguments.
> [fcc] Understand arguments for Coq environment

- CHANGES.md
- coq/loader.ml
`coq-lsp` plugin loader will now be strict in case of a plugin failure, the previous loose behavior was more convenient for the
early releases, but it doesn't make sense now and made things
pretty hard to debug on the Windows installer.
> [coq] [loader] Don't swallow plugin loading errors.

- CHANGES.md
- CONTRIBUTING.md
- README.md
> [doc] Add pointers to Windows installers

- CHANGES.md
- examples/goals.v
- fleche/doc.ml
Fixes #548 ; it'd be nicer when we switch to the more dynamic method.
Thanks to Théo Zimmerman for reporting the problem.
> [fleche] [coq] Recognize `Goal` and `Definition $id : ... .` as proof starters

- CHANGES.md
- controller/rq_common.ml
- controller/rq_common.mli
- controller/rq_definition.ml
- controller/rq_hover.ml
- controller/rq_hover.mli
cc #368 , which is the next step.
> [hover] Refactor providers into plugins, add basic notation display.

- CHANGES.md
- editor/code/package-lock.json
- editor/code/package.json
- editor/code/views/info/tsconfig.json
Quite a few bug fixes that are convenient.
Not sure what happened with the tsconfig.json for the view.
> [client] Update vscode client and misc js packages

- CHANGES.md
- examples/Pff.v
- fleche/theory.ml
- fleche/theory.mli
- lang/lUri.ml
- lang/lUri.mli
We use a simple list, LIFO strategy, which prioritizes the last event.
Fixes #563
> [fleche] Implement document scheduler

- CHANGES.md
- examples/qed_lex.v
- fleche/doc.ml
We do this for when the AST-based method doesn't work, either because of parsing error, or because the `Qed` was parsed as a part of a previous AST, like in `apply Qed.`.
Note that this happens because `Qed.` is not a keyword :p
This implies a huge improvement in usability when editing proofs.
Fixes #33
> [fleche] [error] Detect Qed based on buffer contents

- dune
It's been a while Coq doesn't require that.
> [build] Don't use `-rectypes` on compilation.

- controller/rq_goals.ml
- controller/rq_hover.ml
- fleche/info.ml
- fleche/info.mli
We were doing two calls to find for each goals request.
We now remove unused API as in general the composition of `find` plus a field projection for `Doc.Node.t` was not very useful due to find not being memoized.
> [goals] Remove duplicate call to Info.find

- CHANGES.md
- compiler/fcc.ml
- controller/coq_lsp.ml
- coq/workspace.ml
- coq/workspace.mli
- examples/lists.mv
- test/CoqProject/_CoqProject
- test/CoqProject/test.v
Both in command line, `CoqProject`, and `fcc`.
Fixes: #579
Thanks to Lasse Blaauwbroek for the report.
> [workspace] Support `-rifrom` option.

- CHANGES.md
- README.md
- editor/code/src/client.ts
- editor/code/src/goals.ts
- editor/code/src/node.ts
This way other extensions can implement their own commands that query Coq goals
With #574, close #558
> [client] [vscode] Export Query Goals API

- CHANGES.md
- controller/lsp_core.ml
- controller/request.ml
- controller/rq_hover.ml
- controller/rq_init.ml
- controller/rq_selectionRange.ml
- controller/rq_selectionRange.mli
- etc/doc/PROTOCOL.md
- lsp/core.ml
- lsp/core.mli
We return the range of the Coq sentence underlying the cursor. In VSCode, this is triggered by the "Expand Selection" command.
Note the current implementation is partial: we only take into account the first position, and we only return a single range (Coq sentence) without parents.
This could be of help for #580.
> [lsp] Implement `textDocument/selectionRange`.

- CHANGES.md
- controller/lsp_core.ml
This needs a more principled approach, but should fix the most immediate Windows problems.
Fixes #569
> [workspace] [windows] Tolerate better Windows paths with mixed path separators

- CHANGES.md
- editor/code/views/info/ErrorBrowser.tsx
- editor/code/views/info/Message.tsx
- editor/code/views/info/media/goals.css
- examples/record_print.v
Fixes #457 , fixes #458 , fixes #571
This is a hotfix, but we should actually move this logic to the CoqPp component, as adjusting the breaks at every use doesn't scale.
However this fix should be good for now, as the above fix requires a bit more thinking about the structure of the HTML that contains `Pp`
> [info view] Adjust breaks in errors and messages panels.

- CHANGES.md
- controller/rq_hover.ml
- editor/code/package.json
- editor/code/src/config.ts
- fleche/config.ml
The previous flag was fixed in code, which is way less flexible.
This also fixes a bug in 0.1.8, where the option was left on by mistake.
> [hover] New option `show_loc_info_on_hover` to display parsing debug info.

- Makefile
I think Ali had submitted a request to implement this, but I can't find it now.
> [build] [vendor] Bump submodules + make submodules-update script

- CHANGES.md
- controller/rq_hover.ml
- controller/rq_hover.mli
This is necessary for some use cases, tho we may want to refine later, for example, to provide identifier context.
> [hover] [api] Allow hover access to full document.

- CHANGES.md
- controller/rq_common.ml
- examples/unicode2.v
This was affecting hover and jump to definition.
Thanks to Pierre Courtieu (@matafou) for the example and report.
Closes #594
> [hover] Fix `get_id_at_point` in the presence of Unicode chars

- CHANGES.md
- editor/code/package.json
Suggested by Tomer Chachamu (thanks!) in
https://github.com/microsoft/vscode-discussions/discussions/901
Should fix issue #596 , however I'm not marking this as closed, as this workaround could actually be due to a VSCode bug.
Thanks to Théo Zimmerman for the report.
> [vscode] Workaround broken activation for `.mv` files

- CHANGES.md
- editor/code/package.json
This is required by our use of `vscode-languageclient` 9.
Thanks to Théo Zimmerman for the report.
> [vscode] Require VSCode >= 1.82

- CHANGES.md
- controller/lsp_core.ml
- controller/rq_goals.ml
- controller/rq_goals.mli
- editor/code/lib/types.ts
- etc/doc/PROTOCOL.md
- we rename `pretac` to `command`, as it is a better name
- we allow `mode` to specify the mode without having to reconfigure the server
> [goals] Allow goal mode as LSP parameter, internals

- compiler/compile.ml
- controller/lsp_core.ml
- fleche/doc.ml
- fleche/doc.mli
- fleche/theory.ml
- fleche/theory.mli
This is convenient as we may need to re-create the initial document state when the environment has changed.
This patch doesn't fully take advantage of the document env, but it is a prerequisite for the cleanup in #604, in particular to allow a document to recover on `bump` if the init state failed.
> [fleche] Store document environment in [Doc.t]

- CHANGES.md
- fleche/contents.ml
- fleche/contents.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/theory.ml
- test/server/todo.md
`Doc.t` API has changed: a document that fails to create or update is still valid, but will be set to the right failed state, instead of having the caller handle that case.
This is an important API change in order to implement the upcoming ability to re-check documents on environment changes, which is necessary for jsCoq style hotload, auto-build, to name a few.
> [internal] [fleche] Absorb errors on document creation and update.

- CHANGES.md
- examples/comments_end.v
- fleche/doc.ml
> [fleche] update progress indicator correctly on End Of File

- CHANGES.md
- fleche/config.ml
> [config] set `goal_after_tactic` default to `true`

- compiler/compile.ml
- compiler/driver.ml
- controller/coq_lsp.ml
- controller/rq_goals.ml
- coq/init.ml
- coq/message.ml
- coq/message.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/io.ml
- fleche/io.mli
- fleche/theory.ml
- lang/diagnostic.ml
- lang/diagnostic.mli
- lsp/jLang.ml
- plugins/astdump/main.ml
- plugins/simple/main.ml
- test/compiler/run.t
This is a bit more disciplined and will prevent bugs now that we are writing more and more plugins.
> [internal] Make diagnostic / messages severity types abstract

- .github/workflows/build.yml
- CHANGES.md
- Makefile
- controller/rq_completion.ml
- coq-lsp.opam
- coq/utf8.ml
- coq/utf8.mli
- examples/utf16.v
- flake.nix
- test/unit_test/dune
- test/unit_test/utf16_pos.ml
Fixes #531 
This is probably only a partial as it only affects completion requests.
The translation should probably be done in `lsp_core.ml`, in `do_position_request` for example. But then, what should we do when the position is out of bound? pass None to the implementation? or terminate directly the request?
> Follow LSP and treat positions as UTF16 code units

- CHANGES.md
- controller/lsp_core.ml
- editor/code/package.json
- editor/code/src/config.ts
- fleche/config.ml
- fleche/theory.ml
A new setting `check_only_on_request`, will instruct Flèche to only check documents where data has been demanded.
This doesn't work well with some LSP calls, like `documentSymbols`, as they require the whole document to be processed; if we would try to serve those, we would always proceed to check the documents anyway, defeating the purpose of this PR.
We thus refuse to serve these requests when in this mode.
This setting is just for experimentation, as it is not ready for general, but likely will help people willing to add different navigation strategies as discussed in Zulip.
cc #24
> [fleche] Experimental option for "lazy" document checking.

- .github/workflows/build.yml
Thanks to Etienne Millon for the help.
This also should make OCaml 5.1.1 available in the Windows CI for the future.
Fixes #636
> [ci] [windows] Fix Dune 3.6.1 not available on setup-ocaml

- controller/rq_hover.ml
To be merged synchronously with coq/coq#18443.
> With Coq PR #18443, Prettyp.print_abbreviation takes an additional sigma

- CHANGES.md
- README.md
- compiler/cc.ml
- compiler/compile.ml
- compiler/driver.ml
- controller/coq_lsp.ml
- controller/lsp_core.ml
- controller/lsp_core.mli
- coq/workspace.ml
- coq/workspace.mli
- test/compiler/_CoqProject
This is still not enough, as `CoqProject_file` parser will `exit 1`, but it fixes an important class of bugs that hit early on (initialization phase tries to parse _CoqProject).
> [workspace] Be more resilient to CoqProject errors.

- coq/ast.ml
- coq/ast.mli
- coq/dune
- coq/files.ml
- coq/files.mli
- coq/interp.ml
- coq/interp.mli
- coq/utils.ml
- fleche/doc.ml
- fleche/doc.mli
We add some convenience functions to inspect and evaluate Coq's requires specifically.
Note that we don't yet handle the attributes / control pair of the require, this is required to be fixed before merge (likely requires cut and paste from Coq code + Coq PR to export the relevant functions to do without duplication)
> [coq] API to handle Require Ast specifically

- fleche/doc.ml
- fleche/memo.ml
- fleche/memo.mli
- fleche/perf_analysis.ml
This is required due to the type Require being different.
We generalize the loc-independent caching code.
> [memo] Add memo table for Require.

- .github/workflows/build.yml
- CHANGES.md
- README.md
We also tweak CI config to match what is done in the branches.
> [compat] Drop support for Coq 8.16, update README

- .github/workflows/build.yml
- Windows special config for Coq should not be needed, as we don't build Coq ourselves
- Nix disabled due to #522
> [ci] [v8.19] Try to make CI green again.

- coq-lsp.opam
Versions < 3.13 were broken for composed builds with Coq in scope.
Dune bug was fixed in https://github.com/ocaml/dune/pull/9347
> [dev] [opam] Bump Dune dev version to 3.13

- coq/ast.ml
This is in anticipation of coq/coq#13445 which introduces a new declaration `LetContext` for referring to local definitions introduced by `Context` (while, beforehand, it was using `Definition`). I however wonder whether this is maybe overkell: an alternative would be to use `Let`as we do for local definiitions, renouncing to make a difference between `Let x:=t` and `Context (x:=t)`.
> Adding definition kind LetContext

- CHANGES.md
- compiler/compile.ml
- controller/lsp_core.ml
- fleche/doc.ml
- fleche/doc.mli
This will allow us to:
- postpone the document checking when the require is not ready
- correctly track file dependencies in memoization
- apply the .vo parsing optimization, by intercepting the call
Depends on #643
> [fleche] [doc] Interpret require via special custom path.

- CHANGES.md
- controller/coq_lsp.ml
- controller/lsp_core.ml
- controller/nt_cache_trim.ml
- controller/nt_cache_trim.mli
- controller/rq_goals.ml
- controller/rq_init.ml
- editor/code/package.json
- editor/code/src/client.ts
- etc/doc/PROTOCOL.md
- examples/Rtrigo1.v
- fleche/doc.ml
- fleche/io.ml
- fleche/memo.ml
- fleche/memo.mli
- lsp/io.ml
- lsp/io.mli
New trim command (both in the server and in VSCode) to liberate
space used in the cache.
Command available as
`Coq LSP: Request the server to trim caches and compact memory`
Fixes #367
cc: #253 #236 #348 , which may be greatly alleviated by this PR.
> [memo] Cache control and eviction improvements

- CHANGES.md
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/edit.ts
We add two new VSCode commands to allow to move one sentence backwards / forward, this is particularly useful when combined with lazy checking mode
The code is very hacky, and fully client-side, improvements and further ideas most welcome!
Fixes #263, fixes #580.
I'd propose Meta-n and Meta-P as default keybindings, what do you folks think?
> [vscode] Add simple commands to move backwards / forward in a proof.

- CHANGES.md
- editor/code/package.json
- etc/doc/PROTOCOL.md
- fleche/config.ml
- fleche/doc.ml
- lang/diagnostic.ml
- lang/diagnostic.mli
- lsp/jLang.ml
- We change diagnostics `extra` field to `data`, so we now conform to the LSP spec
- we include the data only when the `send_diags_extra_data` server-side option is enabled
- we now include range of full sentence in error diagnostic extra data
Thanks to @driverag22 for the idea, cc #663
> [diagnostics] Add sentence's range to errors extra `data` field.

- CHANGES.md
- editor/code/src/client.ts
- editor/code/src/config.ts
- editor/code/src/goals.ts
Having to restart the server to change goal display setting was not needed.
Eventually we can expose this setting even the panel UI for easier use if needed.
> [vscode] Have `coq-lsp.pp_type` changes take effect immediately

- editor/code/lib/types.ts
- editor/code/src/client.ts
- editor/code/src/config.ts
- editor/code/src/goals.ts
- editor/code/src/progress.ts
- editor/code/views/info/Info.tsx
While we get approval for implementing full Live Share support in `coq-lsp`, we fix some problems with the current implementation of selectors and API calls for goals, in particular:
- consolidate and implement Coq document selectors into 3 kinds (all, local, vsls documents)
- handle cases for vsls goals request correctly
- expose types for infoView protocol, improve such types
- display info message about goals not available in VSLS
> [vscode] [goals] Handle goal requests better when in Live Share

- CHANGES.md
- editor/code/src/client.ts
- editor/code/src/goals.ts
- etc/doc/PROTOCOL.md
- etc/doc/README.md
- etc/doc/VSCODE_API.md
This allows extensions to register without having to modify ours; it should subsume previous hooks for `VIXZ` and `VIZCAR` visualizers.
There are many more improvements we can do to this API.
Fixes #538
> [vscode] Provide generic user goal request hook.

- CHANGES.md
- coq/workspace.ml
- coq/workspace.mli
- fleche/doc.ml
- fleche/doc.mli
- fleche/theory.ml
- fleche/theory.mli
- plugins/astdump/main.ml
- plugins/goaldump/main.ml
- plugins/save_vo/main.ml
- plugins/simple/main.ml
This way plugins can specify a list of extra imports for each file.
This may compose poorly, so note that in the documentation.
> [fleche] New `InjectRequire` plugin API

- .github/workflows/build.yml
- CHANGES.md
- CONTRIBUTING.md
- coq-lsp.opam
> [build] [doc] [ci] Document and test global opam dev install

- CHANGES.md
- editor/code/package-lock.json
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/views/info/Message.tsx
- flake.lock
This should hopefully help Nix users (cc #684)
We also bump the flake pins, as to grab the newer prettier, thus we include #684 here in the end.
> [dev env] Update prettier to 3.2.5

- .github/workflows/build.yml
Upstream finally includes the fixes for #509
> [vendor] Bump Coq upstream

- CHANGES.md
- editor/code/lib/types.ts
- editor/code/views/perf/App.tsx
- etc/doc/PROTOCOL.md
- fleche/doc.ml
- fleche/doc.mli
- fleche/memo.ml
- fleche/memo.mli
- fleche/perf.ml
- fleche/perf.mli
- fleche/perf_analysis.ml
- fleche/stats.ml
- fleche/stats.mli
We extend `Memo` as to store the original performance execution data, this way, we can display it correctly, and we distinguish the case where a sentence was memoized better.
This is a fix, because before we would display the wrong data for incremental checking.
This is complementary to #686 and #689.
We cherry pick the protocol fixes from #689 as to have this PR in mergeable / testeable shape.
> [fleche] Handle performance data correctly for cached sentences

- editor/code/lib/types.ts
- editor/code/src/perf.ts
- editor/code/views/perf/App.tsx
- editor/code/views/perf/index.tsx
- editor/code/views/perf/tsconfig.json
- etc/doc/PROTOCOL.md
This is useful for #686.
We also fix a misconfiguration of the perf view compilation.
> [code] [types] Generalize TS perf datatype.

- CHANGES.md
- editor/code/package.json
- editor/code/src/client.ts
This makes more sense than the current command behavior which is not usable by almost no one.
> [code] Display JSON data for `coq-lsp.document` in new editor.

- CHANGES.md
- controller/lsp_core.ml
- controller/rq_init.ml
- controller/rq_init.mli
- editor/code/src/client.ts
- etc/doc/PROTOCOL.md
This means that we can finally tweak server options on the fly!
We use the `workspace/didChangeConfiguration` notification, however note that our use is still very rudimentary (and push-based) when compared to the recommended pull model using the
`workspace/configuration` request.
> [lsp] Update server settings on the fly.

- CHANGES.md
- editor/code/src/client.ts
This was likely causing some problems on extension restart.
Still we need to improve how we manage lifetime events.
> [code] Correctly dispose even if client shutdown fails.

- CHANGES.md
- coq/ast.ml
- coq/ast.mli
- coq/protect.ml
- coq/protect.mli
- etc/doc/USER_MANUAL.md
- examples/MetaCommands.v
- fleche/doc.ml
- fleche/memo.ml
- fleche/memo.mli
They are pretty easy to support in our model, and actually I can see how they pretty useful to hint the incremental engine to ignore changes!
For example, see this document:
```coq
(* Coq code 1 ... *)
Lemma foo : ....
(* Coq code 2 ... *)
Reset foo.
(* Coq code 3 ... *)
```
In this case, `Reset` allows us to put a barrier so we can update Coq code 2 at will, and still don't re-check the 3rd code block as it depends on a previous state.
> [fleche] Support Coq Meta Commands Reset and Back

- controller/rq_definition.ml
- fleche/doc.ml
- fleche/doc.mli
- petanque/agent.ml
This is a big improvements for plugins that often use the `toc` as a document access point, for example to do speculative execution.
We also add an option `node.prev` field, which is very useful to go back on document nodes when these where obtained by some other method.
> [fleche] Improve toc to return nodes instead of ranges.

- CHANGES.md
- controller/lsp_core.ml
- editor/code/lib/types.ts
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/config.ts
- etc/doc/PROTOCOL.md
- etc/doc/USER_MANUAL.md
- fleche/theory.ml
- fleche/theory.mli
- lsp/jLang.mli
We introduce a new `coq/viewRange` notification, from client to server, than hints the scheduler about the visible area of the document.
Combined with the new lazy checking mode, this provides checking on scroll, a feature inspired from Isabelle IDE.
TODO:
> [fleche] Auto-check documents on scroll when in lazy mode.

- CHANGES.md
- editor/code/src/client.ts
This seems to fix a few bugs, and makes sense. Not fully sure about the types in the VSCode API tho.
cc: #708
> [code] Wait for shutdown to complete before we start the client again.

- CHANGES.md
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/edit.ts
- etc/doc/USER_MANUAL.md
> [code] Add keybindings for sentenceNext / sentencePrevious

- editor/code/CHANGELOG.md
- editor/code/src/goals.ts
The `Goals` panel is shown in the second column of Vscode. If the user opens a second panel in this column the `Goals` panel may loose focus and proofs and not visible to user when he navigates the proofs again.
This PR, gives the focus back automatically to the `Goals` panel if it has lost it as soon as the user navigates the proofs again.
> Give focus back to Goals panel when navigating proofs

- CHANGES.md
- editor/code/CHANGELOG.md
- editor/code/src/goals.ts
This amends #722, as otherwise keyboard navigation becomes impossible.
We also amend the changelog entry (should be under main)
> [code] Preserve original focus when refocusing the panel.

- examples/ltac2_simple.v
This fixes a SerAPI piercing bug for Ltac2 (sadly creating a segfault)
cc: @afdw
> [deps] Bump Coq and SerAPI

- CHANGES.md
- compiler/args.ml
- compiler/driver.ml
- compiler/fcc.ml
- compiler/output.ml
- compiler/output.mli
- coq/args.ml
- coq/args.mli
- test/compiler/basic/run.t
- test/compiler/exit_code/run.t
New `--diags_level` option for `fcc`.
- `--diags_level=0`: no notice or info
- `--diags_level=1`: notice yes, info no
- `--diags_level=2`: notice yes, info yes
Future:
- `--diags_level=3`: notice yes, info yes, debug yes
but as of today I think Flèche cannot put debug in diagnostics (they are tho shown for goals calls)
> [compiler] Allow control of Coq's info and notice messages.

- README.md
- coq/limits.ml
- etc/doc/USER_MANUAL.md
This very preliminary PR reifies the Coq API so we can pass an interruption / cancellation token around.
Two implementations of the API are provided:
- one using the "classical" `Control.interrupt` variable present in Coq
- one using `memprof-limits` by @gadmm
The code is very preliminary and will likely be rewritten to better accomodate the API, however the current version works, and testing is much appreciated! This is a delicate part of the system so testing is badly needed.
In the examples we had, `memprof-limits` works superb! In particular it works in all the examples where polling fails :D 
I think this should allow us to get rid of Coq polling eventually.
Some open issues:
- While token-based interruption works pretty well, there are a few corner cases where the user experience is …
> [coq] Support for token-based interruption

- lsp/base.ml
We didn't catch this as the server doesn't yet implement any client request.
> [lsp] Fix typo in response parsing.

- .github/workflows/build.yml
- CHANGES.md
- coq-lsp.opam
- petanque/README.md
- petanque/json_shell/dune
- petanque/json_shell/pet.ml
- petanque/json_shell/server.ml
- petanque/json_shell/utils.ml
Add a Petanque TCP server to communicate with Coq.
Bug fixes:
- `Run_error`: unbound (ocaml 5.1.1)
- Second starts with same args raise `ThmNotFound`
> Add a Petanque TCP server

- CHANGES.md
- compiler/compile.ml
- coq/compat.ml
- coq/compat.mli
- coq/glob.ml
- coq/glob.mli
- coq/library_file.ml
- coq/library_file.mli
- petanque/agent.ml
- petanque/agent.mli
- petanque/json_shell/jAgent.ml
- petanque/json_shell/protocol.ml
- petanque/test/basic_api.ml
- petanque/test/json_api.ml
- petanque/test/json_api_failure.ml
We now return the file where the premise is defined, as well as its position and text.
> [petanque] Return extra premise information.

- coq-lsp.opam
Things seem to work pretty well with 0.17.
> [deps] Bump upper bound on JS libs to 0.18

- compiler/compile.ml
- controller/rq_document.ml
- fleche/doc.ml
- fleche/doc.mli
- fleche/theory.ml
- test/serlib/genarg/dune
This was not nice, and not needed anymore.
> [fleche] Remove FailedPermanent 8.16 hack

- CHANGES.md
- fleche/theory.ml
This way we get continuous checking mode when the view-port heuristic is enabled.
> [fleche] Preserve view hint across document changes.

- CHANGES.md
- coq/state.ml
Default parameters where creating lots of collisions, producing chains of hundredths of entries in the memo table.
The new settings seem optimal.
> [coq] [memo] Better parameters for polymorphic state hashing

- CHANGES.md
- controller/nt_cache_trim.ml
- coq/init.ml
- coq/init.mli
- coq/interp.ml
- coq/interp.mli
- coq/workspace.ml
- coq/workspace.mli
- fleche/doc.ml
- fleche/memo.ml
- fleche/memo.mli
We add a basic .vo parsing cache; this often results in large memory savings when working simultaneously with several files.
Based on work from #641 and coq/coq#17393
> [fleche] Caching / sharing of .vo contents

- CHANGES.md
- coq/args.ml
- flake.nix
Currently, `coq-lsp --help` crashed because `Cmdliner` cannot print the default option for `--int-backend`
It would be nicer to have `help` print the possible values of the enum, but I couldn't figure out how.
> Fix help printing

- CHANGES.md
- controller/rq_common.ml
- controller/rq_common.mli
- controller/rq_definition.ml
- controller/rq_hover.ml
- coq/compat.ml
- coq/compat.mli
- coq/glob.ml
- coq/glob.mli
- etc/doc/PROTOCOL.md
- examples/Pff.v
- petanque/agent.ml
For now we use the information in the .glob files, this is to be refined later.
Fixes #317
> [lsp] Jump to definition for non-local definitions

- CHANGES.md
- petanque/agent.ml
- petanque/test/basic_api.ml
We need to rework the protocol as to better reflect the Coq/Flèche workspace mode, but this hotfix will work meanwhile.
> [petanque] Allow `init` to be called multiple times

- CHANGES.md
- fleche/info.ml
- fleche/info.mli
- petanque/agent.ml
This avoids printing and unfreezing, which is no question a performance gain.
> [petanque] Use lighter goal query on run_tac

- CHANGES.md
- petanque/agent.ml
- petanque/agent.mli
- petanque/json_shell/protocol.ml
- petanque/test/basic_api.ml
- petanque/test/json_api.ml
- petanque/test/json_api_failure.ml
We add a new parameter `pre_commands` to `start`, which will be
executed before starting the proof.
> [petanque] Allow to instrument with extra commands before proof start

- CHANGES.md
- petanque/agent.ml
- petanque/agent.mli
- petanque/json_shell/interp.ml
- petanque/json_shell/obj_map.ml
- petanque/json_shell/pet.ml
- petanque/json_shell/protocol.ml
- petanque/json_shell/server.ml
We add a few improvements to the protocol handlers which make the experience of using `pet` from the command line easier:
- http headers can now be disabled by a parameter
- choice of printer for output
- obj_map will handle missing objects id properly
- incoming messages that are not handled are now logged
> [petanque] Improvements on protocol handling

- CHANGES.md
- controller/rq_hover.ml
- controller/rq_hover.mli
- coq/state.ml
- coq/state.mli
- editor/code/package.json
- editor/code/src/config.ts
- fleche/config.ml
Stats seem a bit mixed, more research is needed.
We will improve the analysis shortly, for now we do two kind of analysis:
- on hover, we print the number of universes and constraints at point
- using `fcc --root $abs_path --plugin=coq-lsp.plugin.univdiff $abs_file.v` , the plugin will output an `$abs_file.v.univdiff` file with the following information:
+ a line `univs for "sentence": (nunivs, nconstr) { +diff_nunivs, +diff_constr }` for "sentence"s that have changed the number of universes
+ a summary for `qed` items, where `qed_total: n` is the number of `qed` in the file, and `qed_yes: n` is the number of `qed` that actually changes the universe constraints.
> [hover] Display debug statistic for universes

- CHANGES.md
- coq/ast.ml
- coq/ast.mli
- coq/state.ml
- coq/state.mli
- examples/MetaCommands.v
- fleche/doc.ml
Fixes #550 .
Rest of meta-commands can be supported the same way.
> [fleche] Support `Abort All`.

- compiler/compile.ml
- compiler/driver.ml
- controller/cache.ml
- controller/coq_lsp.ml
- controller/lsp_core.ml
- controller/lsp_core.mli
- controller/nt_cache_trim.ml
- controller/nt_cache_trim.mli
- controller/rq_common.ml
- controller/rq_init.ml
- controller/rq_init.mli
- coq/compat.ml
- coq/compat.mli
- fleche/contents.ml
- fleche/doc.ml
- fleche/info.ml
- fleche/io.ml
- fleche/io.mli
- fleche/theory.ml
- lang/lUri.ml
- lang/lUri.mli
- lsp/io.ml
- lsp/io.mli
- petanque/json_shell/pet.ml
- plugins/astdump/main.ml
- plugins/goaldump/main.ml
- plugins/simple/main.ml
- plugins/univdiff/main.ml
- test/compiler/basic/run.t
We do some cleanup on auxiliary and infra functions:
- use filename output functions from common libs
- add `Format` based logging functions
- remove `Lsp.Io` use to trace, use Fleche Callbacks instead
> [refactor] Consolidation of auxiliary functions.

- CHANGES.md
- petanque/agent.ml
- petanque/agent.mli
- petanque/json_shell/protocol.ml
- petanque/test/basic_api.ml
- petanque/test/json_api.ml
- petanque/test/json_api_failure.ml
A new parameter `memo` to `petanque/run` controls whether the execution is memoized server-side.
`true` by default.
We also rename `run_tac` -> `run` as to be more consistent.
> [petanque] Allow memoization control on `petanque/run`

- CHANGES.md
- controller/dune
- controller/lsp_core.ml
- editor/code/lib/types.ts
- editor/code/package.json
- editor/code/src/client.ts
- editor/code/src/petanque.ts
- examples/petanque.v
- fleche/theory.ml
- fleche/theory.mli
- petanque/README.md
- petanque/agent.ml
- petanque/agent.mli
- petanque/json_shell/interp.ml
- petanque/json_shell/pet.ml
- petanque/json_shell/protocol.ml
- petanque/json_shell/protocol_shell.ml
- petanque/json_shell/server.ml
- petanque/shell.ml
- petanque/shell.mli
- petanque/test/basic_api.ml
This will be very useful for quite a few users, in particular those
willing to interact with Coq from an editor context.
Things integrate pretty well, and `petanque` can demand `Flèche` to
build documents, etc...
Note that we can still improve the codebase a bit, in particular:
- we should share the generic handling code between `controller` and
`petanque`.
- note also the lack of uniformity w.r.t. the cancellation token and
Rq.serve, in particular `Rq.Immediate` and `Rq.query` with result
`Now` should do the same.
> [lsp] [petanque] Allow access to `petanque` protocol from the lsp server

- CHANGES.md
- petanque/agent.ml
- petanque/agent.mli
- petanque/shell.ml
This fixes a bug if `pet-server` was initialized without `--root`
> [petanque] Always initialize default workspace.

- controller/lsp_core.ml
- petanque/json_shell/interp.ml
This is needed otherwise we have a very brittle code w.r.t. the protocol.
> [petanque] Remove duplicity between lsp and pet-server handler.

- CHANGES.md
- coq/goals.ml
- coq/goals.mli
- petanque/agent.ml
- petanque/agent.mli
- petanque/json_shell/interp.ml
- petanque/json_shell/jAgent.ml
- petanque/json_shell/protocol.ml
- petanque/test/basic_api.ml
- petanque/test/json_api.ml
- petanque/test/json_api_failure.ml
This allows the client to implement a state hashtable; see the
comments on the API for low-level details.
Note the changes in `run` result type. I have actually slightly refactored the type; @gbdrt please let me know if that's OK for you, or you would prefer the older type?
> [petanque] New methods `state/eq` and `state/hash`

- serlib/ser_safe_typing.ml
- serlib/ser_safe_typing.mli
To be merged synchronously with coq/coq#19185
> Adapt to Coq PR #19185: flattenting of global_declaration indirection.

- CHANGES.md
- coq-lsp.opam
- lsp/jLang.ml
- lsp/jLang.mli
- lsp/jStdlib.ml
- petanque/json/jAgent.ml
- petanque/json_shell/protocol_shell.ml
It is time to clean up this old compat setup once that #698 has been completed; old `ppx_import` is giving us too much trouble with `petanque`.
> [build] [deps] Bump ppxlib toolchain to 0.26.0.

- CHANGES.md
- examples/ItHolds.v
- serlib/plugins/ltac2/ser_tac2expr.ml
- test/serlib/genarg/ItHolds.v
- test/serlib/genarg/dune
Thanks to Jim Portegies for testing, report, and test case.
> [serlib] Fix wrong piercing of Ltac2 AST + test case

- CHANGES.md
- controller/rq_hover.ml
- examples/print_univs.v
Our code was incomplete. The API here could be really improved Coq-side. About is too verbose for hover, hence our code. We could opt for the version in `prettyp.ml` tho.
Fixes #835
> [hover] Fix universe printing in hover.

- CHANGES.md
- controller/lsp_core.ml
- controller/request.ml
- controller/request.mli
- fleche/theory.ml
- fleche/theory.mli
In this mode, requests are served with whatever document state we have.
This is very useful when we are not in continuous mode, and we don't have a good reference as to what to build, for example in `documentSymbols` (cc: #816)
The mode actually works pretty well in practice as often language requests will come after goals requests, so the info that is needed is at hand.
It could also be tried to set the build target for immediate requests to the view hint, but we should see some motivation for that.
This commit switches `documentSymbols` to the immediate mode, when in lazy checking mode.
> [fleche] New immediate request serving mode.

- CHANGES.md
- etc/doc/PROTOCOL.md
- fleche/doc.ml
- lang/diagnostic.ml
- lang/diagnostic.mli
- lsp/jLang.ml
This fits our use case better.
> [lang] Move `Lang.Diagnostics.Data.t` from a list to name field

- controller/request.ml
- controller/rq_goals.ml
- coq/init.ml
- coq/message.ml
- coq/message.mli
- coq/protect.ml
- coq/protect.mli
- coq/workspace.ml
- fleche/doc.ml
- fleche/doc.mli
- petanque/agent.ml
- plugins/explain_errors/main.ml
- plugins/goaldump/main.ml
This is in preparation for cleaner code in #840
> [coq] Abstract the feedback / error payloads better.

- CHANGES.md
- controller/lsp_core.ml
- controller/rq_action.ml
- controller/rq_action.mli
- controller/rq_goals.ml
- controller/rq_init.ml
- coq/init.ml
- coq/message.ml
- coq/message.mli
- coq/protect.ml
- coq/protect.mli
- examples/Pff.v
- examples/codeAction.v
- fleche/doc.ml
- lang/diagnostic.ml
- lang/diagnostic.mli
- lang/qf.ml
- lang/qf.mli
- lsp/core.ml
- lsp/core.mli
- lsp/jCoq.ml
- lsp/jLang.ml
- lsp/jLang.mli
- lsp/workspace.ml
- lsp/workspace.mli
We provide primitive support for the `textDocument/codeAction` request, for Coq's quickfixes (c.f. coq/coq#19147 )
In particular, we now store the quickfix metadata that Coq may send in the diagnostics extra data, which is then queried by the request handler.
This should not provide a lot of overhead but beware.
We introduce a new kind of `Inmediate` request, this should help with `codeAction` and for `documentSymbol` when in non continuous mode. c.f. #816 
This opens again the question about why errors are processed specially w.r.t. other async data like `feedback`.
This would IMHO require a greater intervention upstream.
> Code Actions

- CHANGES.md
- controller/rq_goals.ml
- etc/doc/PROTOCOL.md
- fleche/doc.ml
- fleche/doc.mli
- petanque/agent.ml
- petanque/test/basic_api.ml
This is a prototype extension.
Note the important change here in behavior here, but IMHO it is
needed: if the commands in `command` fail, we will now fail the
request.
I think in general we may allow some form of error recovery here, but
for now we just let clients recover.
It does seem that CoqPilot / Pytanque do need even a more powerful
interface, but this will allow the them to make some progress for nwo.
Thanks to CoqPilot devs for feedback on this.
> [goals] Allow `command` to process several Coq commands.

- CHANGES.md
- fleche/doc.ml
This was due to incorrect handling of `send_diags_extra_data`
This system needs a bit of rework.
> [fleche] fix quick fixes for errors being lost

- CHANGES.md
- editor/code/syntaxes/coq.json
Add updated syntax from VSCoq Legacy and extend with new commands from Coq 8.17-8.20
> [vscode] Syntax highlighting for Coq 8.17-8.20

- .github/workflows/build.yml
- Makefile
- coq/workspace.ml
To be merged in sync with the upstream PR
> Adapt to https://github.com/coq/coq/pull/19530

- .github/workflows/build.yml
- CHANGES.md
- controller-js/coq_lsp_worker.ml
- controller-js/dune
- controller-js/js_stub/coq_vm.js
- controller-js/js_stub/interrupt.js
- controller-js/js_stub/unix.js
Thanks a lot to Hugo Heuzard for longstanding continued support of the
jsCoq and coq-lsp projects. Without their support these projects would
have never existed.
We also update some other bits to fully account for https://github.com/coq/coq/pull/19530 , worker fully functional again on Coq `master`
> [js worker] Update js_of_ocaml to 5.9.1 and Coq -> Roqc / stdlib split

- serlib/ser_declarations.ml
- serlib/ser_declarations.mli
- serlib/ser_environ.ml
- serlib/ser_mod_declarations.ml
- serlib/ser_mod_declarations.mli
- serlib/ser_safe_typing.ml
I kept the module representations opaque, I doubt that people rely on this through serlib given the mess that this data structure is.
> Adapt w.r.t. coq/coq#19995.

- serlib/ser_declarations.ml
- serlib/ser_declarations.mli
This type is only used internally to the module implementation and is bound to be removed from the API in coq/coq#20061.
> Remove a now internal type from Declarations.

- controller/lsp_core.ml
- fleche/debug.ml
- fleche/doc.ml
- fleche/doc.mli
- fleche/theory.ml
We improve logging about scheduling decisions.
We fix tracing to display the headers again, which was broken in #777 , and perform some other minor cleanups and documentation improvements.
> [fleche] Minor cleanups in scheduling logging

- CHANGES.md
- compiler/driver.ml
- compiler/fcc.ml
- controller-js/coq_lsp_worker.ml
- controller/coq_lsp.ml
- coq/args.ml
- coq/args.mli
- coq/workspace.ml
- coq/workspace.mli
- petanque/json_shell/shell.ml
- test/compiler/basic/run.t
- test/compiler/exit_code/run.t
- test/compiler/long_file/run.t
This is not needed since Coq 8.16, tho the old method wasn't removed until Rocq 9.
> [coq] [workspace] Remove machinery for old-style manual ML path handling

- CHANGES.md
- compiler/driver.ml
- compiler/output.ml
- controller-js/coq_lsp_worker.ml
- controller/coq_lsp.ml
- controller/lsp_core.ml
- controller/rq_init.ml
- fleche/debug.ml
- fleche/io.ml
- fleche/io.mli
- lsp/base.ml
- lsp/base.mli
- lsp/io.ml
- lsp/io.mli
- petanque/json_shell/client.ml
- petanque/json_shell/interp_shell.ml
- petanque/json_shell/pet.ml
- petanque/json_shell/shell.ml
- petanque/json_shell/shell.mli
- petanque/test/basic_api.ml
This is a step towards fixing an apparent bug in coq-lsp not respecting `$/setTrace("off")`.
We consolidate tracing in `Fleche.Io` as tracing is really a Flèche facility.
We add a way to log to a file (as to help with #868 ), so we can see the low-level protocol format better. This corrects a minor regression from #130.
> [lsp] Cleanup of LSP IO

- coq/args.ml
- petanque/json_shell/shell.ml
This doesn't feel very satisfying but IDK what else to do.
> Adapt to coq/coq#19901 (relocatable mode)

- Makefile
We bump submodules to handle incompatible changes, and fix the `make submodules-update` target as to also bump waterproof.
> [vendor] Bump coq and coq-waterproof, fix auto-update script

- serlib/plugins/funind/ser_g_indfun.ml
- serlib/ser_constr.ml
- serlib/ser_constr.mli
- serlib/ser_pattern.ml
- serlib/ser_sorts.ml
- serlib/ser_stdarg.ml
- serlib/ser_univGen.ml
- serlib/ser_univGen.mli
- serlib/ser_vernacexpr.ml
Remove `Sorts.family` and serialize `QualityOrSet` that replace the `Sorts.family` during schemes generation.
> Adapt to rocq-prover/rocq#20397

- CHANGES.md
- etc/FAQ.md
Fixes #817
[Rendered](https://github.com/ejgallego/coq-lsp/blob/c78878076de359b7f46eda4368970b4e83da2a7e/etc/FAQ.md)
> [faq] Update FAQ for VsCoq 2 release.

- CHANGES.md
- editor/code/package.json
On macOS `Cmd+N` is used for creating a new file, `Cmd+P` is "Go to file ..." - both are fundamental editor features, - that this extension breaks by introducing conflicting key binds.
macOS doesn't have a `Meta+` key prefix [(You can see the available prefixes here)](https://code.visualstudio.com/docs/editor/keybindings#_accepted-keys). `Alt+Enter` is used for "select all" during search and for other cases here and there. In addition, it's used by a popular GitLens extension. I propose `Alt+Shift+enter` as a new key combination, at least on macOS.
> VSCode extension keybindings shouldn't conflict with editor defaults.

- CHANGES.md
- controller/lsp_core.ml
- coq/limits.ml
- coq/version.ml
- coq/version.mli
- fleche/doc.mli
Released Rocq versions are not safe yet, see rocq-prover/rocq#19177
You can enable it using the `--int_backend=Mp` command line parameter.
> [rocq] Disable memprof-limits interruption backend by default

- CHANGES.md
- controller/dune
- controller/lsp_core.ml
- controller/request.ml
- controller/request.mli
- controller/rq_action.mli
- controller/rq_completion.mli
- controller/rq_definition.ml
- controller/rq_definition.mli
- controller/rq_document.mli
- controller/rq_goals.mli
- controller/rq_hover.mli
- controller/rq_lens.mli
- controller/rq_selectionRange.mli
- controller/rq_symbols.mli
- etc/doc/PROTOCOL.md
- lsp/base.ml
- lsp/base.mli
- petanque/json/dune
- petanque/json/interp.ml
- petanque/json/interp.mli
- petanque/json_shell/interp_shell.ml
We use the optional `data` field from the LSP specification.
This is useful to be able to obtain feedback messages such as debug messages even when a request fails.
This also opens the door to better protocol handling and petanque integration.
We don't't update the VSCode to use this yet, but maybe we should do it soon.
> [controller] [lsp] Include Rocq feedback on request errors.

- CHANGES.md
- controller/request.ml
- controller/request.mli
- petanque/agent.ml
- petanque/agent.mli
- petanque/dune
- petanque/json/interp.ml
- petanque/json/interp.mli
- petanque/json/jAgent.ml
- petanque/json/protocol.ml
- petanque/json_shell/interp_shell.ml
- petanque/json_shell/interp_shell.mli
- petanque/json_shell/pet.ml
- petanque/json_shell/server.ml
- petanque/json_shell/shell.ml
- petanque/json_shell/shell.mli
- petanque/test/basic_api.ml
- petanque/test/json_api.ml
- petanque/test/test.v
This is important for many use cases. We also return feedback on petanque errors.
cc: @JulesViennotFranca
> [petanque] Add feedback field to errors and `Run_result.t`

- CHANGES.md
- controller/lsp_core.ml
- petanque/agent.ml
- petanque/agent.mli
- petanque/json/interp.ml
- petanque/json/interp.mli
- petanque/json/protocol.ml
- petanque/json_shell/client.ml
- petanque/json_shell/client.mli
- petanque/json_shell/interp_shell.ml
We also introduce a position action so petanque requests can wait on the position. Written by Jules, with some cleanups by me.
Note we tweak some parameters to follow LSP names, like `line` and `character` for positions.
> [petanque] Add `get_state` calls

- CHANGES.md
- editor/code/package.json
- editor/code/syntaxes/markdown-coq-codeblock.json
- fleche/contents.ml
> [fleche] Support "rocq" markdown delimiters in .mv files

- CHANGES.md
- lsp/jLang.ml
- serlib/serlib_base.ml
This was making URI parsing errors very hard to catch, thanks to Adrian in Zulip for noticing this.
> [lsp] Don't raise on URI parsing error.

- fleche/io.ml
We now print the messages; note that in many operations (for example error recovery) non-user-facing feedback is expected.
> [fleche] [io] [nit] Improve logging for unexpected feedback.

- CHANGES.md
- CONTRIBUTING.md
- controller/rq_completion.ml
- controller/rq_goals.ml
- controller/unicode_bindings.ml
- editor/code/package.json
- editor/code/src/config.ts
- etc/doc/PROTOCOL.md
- fleche/config.ml
- lsp/jFleche.ml
All info returned by a `proof/goals` request should be about the sentence requested by the user, whereas currently only `goals` follows this, and `messages`, `error` and `range` are about the sentence under point instead. IMO this is bad UX and may mislead users, as the goal display is de-correlated from the associated info and error messages and range indicators.
There is no loss of information here, as anyways diagnostics are sent back with their range info using the usual LSP mechanisms, and the user can peruse those under point using the standard method of their editor.
WDYT?
PS: I didn't put anything under the changelogs because I don't know what the policy is esp. regarding versioning (this is a breaking change).
fix: #941
> [lsp] Return executed sentence info in goal request.

- editor/code/src/config.ts
VSCode will use a proxy for non-literal config values, which will make the LSP Workers fail to initialize due `postMessage` failing.
We workaround that, in the hopes it doesn't occur too often.
This was introduced in #993
> [code] [web] Fix server config error due to proxy value.

- CHANGES.md
- README.md
- etc/FAQ.md
- etc/SerAPI.md
- etc/doc/PROTOCOL.md
- etc/doc/README.md
- etc/doc/USER_MANUAL.md
- fleche/contents.ml
Extension commands, binaries, and code will be done in 0.3, as they are not backwards compatible.
We also add support for `\begin{rocq}` in literate TeX mode.
cc: #933
> [meta] Rename Coq -> Rocq in documentation files.
